/*
 * Hard coding: writing character cards into About Me markup by hand instead of
 * letting JanitorAI generate them.
 *
 * Why anyone would: the site's own card grid is generated by its React app, so
 * its class names change without warning and a theme built on them breaks. A
 * hardcoded card is your own markup with your own class names — it cannot be
 * rearranged under you. The cost is that everything the site filled in for you
 * (name, description, tags, the link, the art) now has to be typed out, once
 * per character, in five different places. That is what this module does for
 * you.
 *
 * It owns two things:
 *
 *   1. the roster — a list of characters, which the Cards panel edits and
 *      `fromDocument` can read straight out of a captured profile;
 *   2. the emitters — which turn that roster into the markup, and into the
 *      slice of CSS that scales with it (which file is the default, which
 *      `:target` shows which, the filter chips). Everything decorative stays
 *      in the creator's own stylesheet: this only writes the wiring, between
 *      markers, so regenerating never touches a line they wrote.
 *
 * The layout it emits for is "contact select": a stage on one side, a roster
 * of tiles on the other, selection carried by :target because JanitorAI strips
 * every scriptable element. More layouts can be added as more emitters.
 */
(function (global) {
  'use strict';

  var HTML_START = '<!-- @jai:hardcode:start -->';
  var HTML_END = '<!-- @jai:hardcode:end -->';
  var CSS_START = '/* @jai:hardcode:start */';
  var CSS_END = '/* @jai:hardcode:end */';
  var STYLE_START = '/* @jai:hardcode:style:start */';
  var STYLE_END = '/* @jai:hardcode:style:end */';

  var DEFAULTS = {
    title: 'Contact\nSelect',
    kicker: 'Choose a file',
    status: 'Agent archive / online',
    launch: 'Open encounter ↗',
    slots: 7,
    accent: '#ff8a1f',
    preview: '#739dff',
    ink: '#080a09',
    filters: true,
    filterLimit: 8,
    style: 'none',
    gridMaxHeight: '47vh',
    tileMinWidth: '84px',
    profileLabel: 'INTER-KNOT / CREATOR CHANNEL',
    profileMark: 'PROXY',
    aboutTitle: 'Behind the screen.',
    aboutBody: 'This is your corner of the terminal. Add who you are, the worlds you like writing, and what people can expect from your characters.',
    creatorNotes: 'Room for your current projects, release notes, and the things you want visitors to know before they jump into a chat.',
    friendsTitle: 'The inner circle.',
    discord: 'https://discord.gg/e2HDbWXUBp',
    footerText: 'Choose a file. Enter a story.',
    // Profile Information (js/profile-info.js). Every list is optional: a
    // layout keeps its open slots until the creator adds their own.
    username: '',
    sections: null,
    friends: null,
    socials: null,
    // The Steam profile layout (js/steam-profile.js).
    identity: null,
    inventory: null,
    workshop: null,
    steamTheme: 'default',
    // '' = your picture if there is one, otherwise the theme's own backdrop.
    steamBackdrop: '',
    steamBackground: '',
    steamFrame: 'none',
    steamFrameImage: '',
    steamLevel: '',
    steamStatus: 'Currently Online',
    steamSubtitle: '',
    // The Instagram-style design: Golden Hour's own parts, with their copy
    // written from Profile data (js/photo-feed-profile.js).
    feedName: '',
    feedCategory: 'Bot creator',
    feedStories: true
  };

  /* A design with markup all of its own writes it itself; the rest share the
   * contact-select markup below. */
  function ownEmitter(o) {
    if (o.style === 'steam') return global.JaiSteamProfile || null;
    return null;
  }

  // ------------------------------------------------------------------ text

  function esc(value) {
    return String(value == null ? '' : value)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  function attr(value) {
    return esc(value).replace(/"/g, '&quot;');
  }

  /* A CSS string literal: content: "…" has to survive quotes in a name. */
  function cssString(value) {
    return '"' + String(value == null ? '' : value).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
  }

  function slugify(name) {
    return String(name || '').toLowerCase()
      .normalize('NFD').replace(/[̀-ͯ]/g, '')
      .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'file';
  }

  /* Two digits, the way the layout labels files: 1 -> "01". */
  function pad(n) { return (n < 10 ? '0' : '') + n; }

  /*
   * The giant watermark behind the stage is the name broken over short lines.
   * Three characters a line matches the proportions the layout was drawn at;
   * a short name stays on one.
   */
  function markLines(name) {
    var letters = String(name || '').replace(/\s+/g, '');
    if (letters.length <= 4) return [letters.toUpperCase()];
    var out = [];
    for (var i = 0; i < letters.length && out.length < 3; i += 3) {
      out.push(letters.slice(i, i + 3).toUpperCase());
    }
    return out;
  }

  // ------------------------------------------------------------- the roster

  /* Fills in what the emitters need and nothing more; every field is optional
   * to the person typing, so every field has to be optional here too. */
  function normalise(entry, index, taken) {
    var name = String((entry && entry.name) || '').trim() || ('File ' + (index + 1));
    var id = slugify(entry && entry.id ? entry.id : name);
    if (taken) {
      var base = id, n = 2;
      while (taken[id]) { id = base + '-' + n++; }
      taken[id] = true;
    }
    var tags = entry && entry.tags ? entry.tags : [];
    if (typeof tags === 'string') tags = tags.split(',');
    tags = tags.map(function (t) { return String(t).trim(); }).filter(Boolean);
    var portrait = String((entry && entry.portrait) || '').trim();
    var art = String((entry && entry.art) || '').trim();

    // One image is enough to make a complete contact. A creator can still
    // override either role, but the bot's ordinary image fills both by default.
    if (!portrait) portrait = art;
    if (!art) art = portrait;

    return {
      id: id,
      name: name,
      tagline: String((entry && entry.tagline) || '').trim(),
      quote: String((entry && entry.quote) || '').trim(),
      description: String((entry && entry.description) || '').trim(),
      tags: tags,
      link: String((entry && entry.link) || '').trim(),
      portrait: portrait,
      art: art,
      hover: String((entry && entry.hover) || '').trim(),
      chats: String((entry && entry.chats) || '').trim(),
      tokens: String((entry && entry.tokens) || '').trim(),
      featured: !!(entry && entry.featured)
    };
  }

  function prepare(roster) {
    var taken = {};
    return (roster || []).map(function (entry, i) { return normalise(entry, i, taken); });
  }

  function options(opts) {
    var out = {};
    Object.keys(DEFAULTS).forEach(function (k) {
      out[k] = opts && opts[k] != null && opts[k] !== '' ? opts[k] : DEFAULTS[k];
    });
    out.slots = Math.max(out.slots, 0);
    return out;
  }

  /*
   * Which tags earn a filter chip. Every tag on every character would be a wall
   * of chips, so: linkable tags only (a rating like "Limitless" filters
   * nothing), and sorted by how many characters carry them, most-shared first —
   * a chip that narrows nothing is not worth the row space.
   */
  function filterTags(files, limit, chosen) {
    var counts = {}, labels = {};
    files.forEach(function (file) {
      var seen = {};
      file.tags.forEach(function (tag) {
        if (!global.JaiTags.isLinkable(tag)) return;
        var key = global.JaiTags.slug(tag);
        if (seen[key]) return;
        seen[key] = true;
        counts[key] = (counts[key] || 0) + 1;
        labels[key] = global.JaiTags.label(tag);
      });
    });
    // An explicit list wins: "most shared first" is a decent guess, but only
    // the creator knows which six chips are worth the row.
    if (chosen && chosen.length) {
      return chosen.map(function (name) {
        var key = global.JaiTags.slug(name);
        return { key: key, label: labels[key] || global.JaiTags.label(name), count: counts[key] || 0 };
      }).filter(function (t) { return t.key; });
    }
    return Object.keys(counts)
      .sort(function (a, b) { return counts[b] - counts[a] || a.localeCompare(b); })
      .slice(0, limit == null ? 8 : limit)
      .map(function (key) { return { key: key, label: labels[key], count: counts[key] }; });
  }

  /* `filters` is true for automatic chips, false/0 for none, or a list (array
   * or comma string) to choose them by hand. */
  function chosenFilters(value) {
    if (typeof value === 'string' && value.trim()) return value.split(',');
    if (Array.isArray(value)) return value;
    return null;
  }

  // ----------------------------------------------------------------- markup

  /*
   * An <img> only earns its place if the address survives the paste. A capture
   * rewrites its images to blob: urls that live in this browser tab and nowhere
   * else, so one of those in a profile is a broken image for everyone but you.
   */
  function usable(src) {
    return /^(https?:)?\/\//i.test(String(src || '').trim());
  }

  function tagChip(tag) {
    var label = esc(global.JaiTags.label(tag));
    if (!global.JaiTags.isLinkable(tag)) return '<span>' + label + '</span>';
    return '<a href="' + attr(global.JaiTags.url(tag)) + '">' + label + '</a>';
  }

  /*
   * One line, deliberately: a newline between two inline-level tags is a real
   * space once it renders, and these chips sit inline. See the layout warnings
   * the linter raises for hand-written markup with the same shape.
   */
  function markup(roster, opts) {
    var files = prepare(roster);
    var o = options(opts);
    if (!files.length) return '';
    var own = ownEmitter(o);
    if (own) return own.markup(files, o);
    var filters = o.filters ? filterTags(files, o.filterLimit, chosenFilters(o.filters)) : [];
    var html = [];

    if (o.style === 'proxy-terminal') html.push(proxyOpen());
    html.push('<section class="cs-shell" id="contact-select">');
    files.forEach(function (f) { html.push('<span class="cs-key" id="sig-' + attr(f.id) + '"></span>'); });
    if (filters.length) {
      html.push('<span class="cs-key" id="f-all"></span>');
      filters.forEach(function (t) { html.push('<span class="cs-key" id="f-' + attr(t.key) + '"></span>'); });
    }

    html.push('<section class="cs-roster" aria-label="Character selector">');

    if (filters.length) {
      html.push('<div class="cs-filters" aria-label="Filter by tag">');
      html.push('<a class="cs-filter cs-filter-all" href="#f-all">All</a>');
      filters.forEach(function (t) {
        html.push('<a class="cs-filter cs-filter-' + attr(t.key) + '" href="#f-' + attr(t.key) + '">' +
          esc(t.label) + '</a>');
      });
      html.push('</div>');
    }

    html.push('<div class="cs-roster-head"><strong>' +
      esc(o.title).replace(/\n/g, '<br>') + '</strong><span>' + esc(o.kicker) + '</span></div>');

    html.push('<div class="cs-grid">');
    files.forEach(function (f, i) {
      var classes = ['cs-slot', 'cs-slot-live', 'cs-slot-' + f.id];
      f.tags.forEach(function (tag) {
        if (global.JaiTags.isLinkable(tag)) classes.push('cs-t-' + global.JaiTags.slug(tag));
      });
      html.push('<a class="' + attr(classes.join(' ')) + '" href="#sig-' + attr(f.id) +
        '" aria-label="' + attr('Select file ' + pad(i + 1) + ', ' + f.name) + '">');
      html.push('<span class="cs-slot-face">');
      if (usable(f.portrait)) {
        html.push('<img class="cs-slot-thumb" src="' + attr(f.portrait) + '" alt="' +
          attr(f.name + ' portrait') + '">');
      }
      html.push('</span>');
      if (usable(f.hover)) html.push('<img class="cs-stage-preview" src="' + attr(f.hover) + '" alt="">');
      html.push('</a>');
    });
    for (var s = files.length; s < o.slots; s++) {
      html.push('<div class="cs-slot" aria-hidden="true"><span class="cs-slot-face"></span></div>');
    }
    html.push('</div>');

    files.forEach(function (f) {
      if (!f.tags.length) return;
      html.push('<div class="cs-tags cs-tags-' + attr(f.id) + ' cs-for-' + attr(f.id) +
        '" aria-label="' + attr(f.name + ' profile tags') + '">');
      f.tags.forEach(function (tag) { html.push(tagChip(tag)); });
      html.push('</div>');
    });

    html.push('<div class="cs-select-line">');
    files.forEach(function (f, i) {
      html.push('<span class="cs-for-' + attr(f.id) + '">Subject ' + pad(i + 1) + ' / ready</span>');
    });
    files.forEach(function (f) {
      if (!f.link) return;
      html.push('<a class="cs-launch cs-for-' + attr(f.id) + '" href="' + attr(f.link) + '">' +
        esc(o.launch) + '</a>');
    });
    html.push('</div></section>');

    html.push('<div class="cs-scene">');
    files.forEach(function (f) {
      if (!usable(f.art)) return;
      html.push('<img class="cs-scene-art cs-art-' + attr(f.id) + '" src="' + attr(f.art) +
        '" alt="' + attr(f.name + ' key art') + '">');
    });
    html.push('<div class="cs-scene-shade"></div>');
    files.forEach(function (f) {
      html.push('<div class="cs-scene-mark cs-for-' + attr(f.id) + '">' +
        markLines(f.name).map(esc).join('<br>') + '</div>');
    });
    html.push('</div>');

    html.push('<div class="cs-topline"><span class="cs-topline-status"><i></i> ' +
      esc(o.status) + '</span>');
    files.forEach(function (f, i) {
      html.push('<span class="cs-topline-file cs-for-' + attr(f.id) + '">File ' + pad(i + 1) +
        ' · Selected character</span>');
    });
    html.push('</div>');

    files.forEach(function (f, i) {
      html.push('<div class="cs-identity cs-for-' + attr(f.id) + '">');
      html.push('<span class="cs-code">' + pad(i + 1) + ' · Active contact</span>');
      html.push('<h1 class="cs-name">' + esc(f.name) + '</h1>');
      if (f.tagline) html.push('<p class="cs-title">' + esc(f.tagline) + '</p>');
      if (f.quote) html.push('<p class="cs-quote">' + esc(f.quote) + '</p>');
      if (f.description) html.push('<p class="cs-desc">' + esc(f.description) + '</p>');
      html.push('</div>');
    });

    files.forEach(function (f, i) {
      html.push('<span class="cs-index cs-for-' + attr(f.id) + '">Selection complete · ' +
        pad(i + 1) + ' / ' + pad(Math.max(o.slots, files.length)) + '</span>');
    });

    html.push('</section>');
    if (o.style === 'proxy-terminal') html.push(proxyClose(o));
    return html.join('');
  }

  function proxyOpen() {
    return '<div class="zz-navigation"><span class="zz-nav-key" id="zz-agents"></span><span class="zz-nav-key" id="zz-about"></span><span class="zz-nav-key" id="zz-friends"></span><span class="zz-nav-key" id="zz-links"></span><nav class="zz-nav" aria-label="Profile screens"><a class="zz-tab zz-tab-agents" href="#zz-agents"><small>01</small> Agents</a><a class="zz-tab zz-tab-about" href="#zz-about"><small>02</small> About me</a><a class="zz-tab zz-tab-friends" href="#zz-friends"><small>03</small> Friends</a><a class="zz-tab zz-tab-links" href="#zz-links"><small>04</small> Links</a></nav><span class="zz-nav-meta"><i></i> PERSONAL TERMINAL</span></div>' +
      '<section class="zz-screen zz-agents" aria-label="Agent archive"><div class="zz-stage-heading"><span><b>CHARACTER ARCHIVE</b> &nbsp; / &nbsp; CHOOSE YOUR NEXT ENCOUNTER</span><span>PERSONAL COLLECTION</span></div>';
  }

  /* Text typed into a textarea keeps its line breaks. */
  function multiline(value) { return esc(value).replace(/\r?\n/g, '<br>'); }

  function initial(name) { return String(name || '').trim().charAt(0).toUpperCase(); }

  /* A link with no label of its own is named after its site. */
  function siteName(link) {
    return String(link || '').replace(/^https?:\/\/(www\.)?/i, '').split(/[/?#]/)[0];
  }

  function proxyClose(o) {
    var sections = (o.sections || []).filter(function (s) { return s && (s.title || s.body); });
    var friends = (o.friends || []).filter(function (f) { return f && (f.name || usable(f.link)); });
    var socials = (o.socials || []).filter(function (s) { return s && usable(s.link); });
    return '</section>' + proxyAbout(o, sections) + proxyFriends(o, friends) + proxyLinks(o, socials) +
      '<div class="zz-footer"><span>PROXY TERMINAL' +
      (o.username ? ' / ' + esc(String(o.username).toUpperCase()) : '') +
      '</span><span>' + esc(o.footerText) + ' <a href="#zz-agents">↖ Back to agents</a></span></div>';
  }

  function proxyAbout(o, sections) {
    var logs = sections.length
      ? sections.map(function (s) {
        return '<details class="zz-log"><summary>' + esc(s.title || 'Notes') + '</summary><p>' +
          multiline(s.body) + '</p></details>';
      }).join('')
      : '<details class="zz-log"><summary>Before you connect</summary><p>Add your boundaries, content notes, or roleplay preferences here.</p></details>';
    return '<section class="zz-screen zz-personal zz-about-screen" aria-label="About me"><span class="zz-eyebrow">02 / Personal file</span><h2>' + esc(o.aboutTitle) + '</h2><div class="zz-about-grid"><article class="zz-bio-card"><p class="zz-big-copy">A little introduction goes a long way.</p><p>' + multiline(o.aboutBody) + '</p></article><div><details class="zz-log" open><summary>Creator notes</summary><p>' + multiline(o.creatorNotes) + '</p></details>' + logs + '</div></div></section>';
  }

  /* Open slots stay until the creator adds someone: an empty Friends screen
   * reads as unfinished, three invitations read as intentional. */
  function proxyFriends(o, friends) {
    var cards = friends.length
      ? friends.map(function (f, i) {
        var face = usable(f.image)
          ? '<img src="' + attr(f.image) + '" alt="' + attr(f.name || '') + '">'
          : esc(initial(f.name) || '+');
        var body = '<span>' + face + '</span><h3>' + esc(f.name || 'Friend / ' + pad(i + 1)) + '</h3>' +
          (f.note ? '<p>' + multiline(f.note) + '</p>' : '');
        return usable(f.link)
          ? '<a class="zz-friend zz-friend-link" href="' + attr(f.link) + '">' + body + '</a>'
          : '<article class="zz-friend">' + body + '</article>';
      }).join('')
      : '<article class="zz-friend"><span>+</span><h3>Open channel / 01</h3><p>A spot for a friend.<br>Add their name, profile link and a little introduction.</p></article><article class="zz-friend"><span>+</span><h3>Open channel / 02</h3><p>A spot for a creator you love.<br>Give visitors someone new to discover.</p></article><article class="zz-friend"><span>+</span><h3>Open channel / 03</h3><p>Keep your circle growing.<br>This channel is ready when you are.</p></article>';
    return '<section class="zz-screen zz-personal zz-friends-screen" aria-label="Friends"><span class="zz-eyebrow">03 / Your people</span><h2>' + esc(o.friendsTitle) + '</h2><p>Good stories. Better company. A space for your friends and favorite creators.</p><div class="zz-friend-grid">' + cards + '</div></section>';
  }

  function proxyLinks(o, socials) {
    var links;
    if (socials.length) {
      links = socials.map(function (s, i) {
        var icon = usable(s.image) ? '<img class="zz-social-icon" src="' + attr(s.image) + '" alt="">' : '';
        return '<a class="zz-social" href="' + attr(s.link) + '"><small>' + icon + 'Channel / ' + pad(i + 1) +
          '</small><strong>' + esc(s.label || siteName(s.link)) + ' <b>↗</b></strong></a>';
      }).join('');
    } else {
      // Rosters saved before Profile Information had a single Discord field.
      var discord = usable(o.discord) ? attr(o.discord) : '#zz-links';
      links = '<a class="zz-social" href="' + discord + '"><small>COMMUNITY / INVITE</small><strong>Discord <b>↗</b></strong></a><div class="zz-social zz-social-empty"><small>YOUR NEXT CHANNEL</small><strong>Space for your socials <b>+</b></strong><p>Add your website, art page, or another social profile.</p></div>';
    }
    return '<section class="zz-screen zz-personal zz-links-screen" aria-label="Social links"><span class="zz-eyebrow">04 / Outside the terminal</span><h2>Stay <em>connected.</em></h2><p>Another channel. The same creator.</p><div class="zz-social-list">' + links + '</div></section>';
  }

  // -------------------------------------------------------------------- css

  /*
   * Only the rules that scale with the roster. The first file is the one with
   * no hash in the URL, so it needs no :target rules of its own — it just has
   * to hand its styling back when something else is selected.
   */
  function css(roster, opts) {
    var files = prepare(roster);
    var o = options(opts);
    if (!files.length) return '';
    var own = ownEmitter(o);
    if (own) return own.css(files, o);
    var first = files[0];
    var rest = files.slice(1);
    var filters = o.filters ? filterTags(files, o.filterLimit, chosenFilters(o.filters)) : [];
    var out = [];

    function targeted(file, tail) { return '#sig-' + file.id + ':target ~ ' + tail; }
    function eachRest(tail) {
      return rest.map(function (f) { return targeted(f, tail); }).join(',\n');
    }

    out.push('/* Generated from the Cards panel — edit the roster there, not here. */');
    out.push('');
    out.push('/* A roster is any size, so it is capped here rather than left to stretch the');
    out.push(' * page: tiles wrap by width, and the grid scrolls once it runs out of height.');
    out.push(' * The stage previews are positioned against .cs-shell, above this scroller,');
    out.push(' * so they still paint over the stage instead of being clipped into a tile. */');
    out.push('.cs-grid { grid-template-columns: repeat(auto-fill, minmax(' + o.tileMinWidth +
      ', 1fr)); max-height: ' + o.gridMaxHeight + '; overflow-y: auto; }');

    if (rest.length) {
      out.push(rest.map(function (f) { return '.cs-for-' + f.id; }).join(', ') + ' { display: none; }');
    }
    out.push('.cs-art-' + first.id + ' { opacity: 1; }');
    out.push('');

    out.push('/* File number and name plate on each tile. */');
    files.forEach(function (f, i) {
      out.push('.cs-slot-' + f.id + ' .cs-slot-face::before { content: ' + cssString(pad(i + 1)) + '; }');
      out.push('.cs-slot-' + f.id + ' .cs-slot-face::after { content: ' +
        cssString(f.name.toUpperCase()) + '; }');
      if (f.tags.length) {
        out.push('.cs-tags-' + f.id + '::before { content: ' +
          cssString('PROFILE TAGS / ' + pad(i + 1)) + '; }');
      }
    });
    out.push('');

    out.push('/* The selected tile. */');
    out.push(['.cs-slot-' + first.id + ' .cs-slot-face']
      .concat(rest.map(function (f) { return targeted(f, '.cs-roster .cs-slot-' + f.id + ' .cs-slot-face'); }))
      .join(',\n') + ' {');
    out.push('  border: 4px solid ' + o.accent + ';');
    out.push('  background: #151916;');
    out.push('  box-shadow: 0 0 0 3px ' + o.ink + ', 8px 8px 0 ' + o.ink + ';');
    out.push('  transform: skewY(-2deg) scale(1.08) translateY(-3px);');
    out.push('}');
    out.push(['.cs-slot-' + first.id + ' .cs-slot-face::before']
      .concat(rest.map(function (f) { return targeted(f, '.cs-roster .cs-slot-' + f.id + ' .cs-slot-face::before'); }))
      .join(',\n') + ' { color: ' + o.accent + '; }');
    out.push(['.cs-slot-' + first.id + ' .cs-slot-thumb']
      .concat(rest.map(function (f) { return targeted(f, '.cs-roster .cs-slot-' + f.id + ' .cs-slot-thumb'); }))
      .join(',\n') + ' { filter: contrast(1.06) saturate(.98); }');
    out.push('');

    if (rest.length) {
      out.push('/* …and the default file hands that styling back when it is not the open one. */');
      out.push(eachRest('.cs-roster .cs-slot-' + first.id + ' .cs-slot-face') + ' {');
      out.push('  border: 1px solid #3b403c;');
      out.push('  background: repeating-linear-gradient(135deg, transparent 0 8px, #ffffff09 9px, transparent 10px), #111412;');
      out.push('  box-shadow: none;');
      out.push('  transform: skewY(-2deg);');
      out.push('}');
      out.push(eachRest('.cs-roster .cs-slot-' + first.id + ' .cs-slot-face::before') + ' { color: #8f9791; }');
      out.push(eachRest('.cs-roster .cs-slot-' + first.id + ' .cs-slot-thumb') +
        ' { filter: saturate(.5) brightness(.66) contrast(1.08); }');
      out.push('');
    }

    out.push('/* The open file never previews itself: a click reads as the blue');
    out.push(' * hover art dropping straight into full colour. */');
    out.push('.cs-slot-' + first.id + ':hover .cs-slot-face { border: 4px solid ' + o.accent +
      '; box-shadow: 0 0 0 3px ' + o.ink + ', 8px 8px 0 ' + o.ink + '; }');
    out.push('.cs-slot-' + first.id + ':hover .cs-slot-thumb { filter: contrast(1.1) saturate(1.02) brightness(1.04); }');
    out.push('.cs-slot-' + first.id + ':hover .cs-stage-preview,\n.cs-slot-' + first.id +
      ':hover::after { opacity: 0; }');
    rest.forEach(function (f) {
      out.push(targeted(f, '.cs-roster .cs-slot-' + f.id + ':hover .cs-slot-face') +
        ' { border: 4px solid ' + o.accent + '; box-shadow: 0 0 0 3px ' + o.ink + ', 8px 8px 0 ' + o.ink + '; }');
      out.push(targeted(f, '.cs-roster .cs-slot-' + f.id + ':hover .cs-slot-thumb') +
        ' { filter: contrast(1.1) saturate(1.02) brightness(1.04); }');
      out.push(targeted(f, '.cs-roster .cs-slot-' + f.id + ':hover .cs-stage-preview') + ',\n' +
        targeted(f, '.cs-roster .cs-slot-' + f.id + ':hover::after') + ' { opacity: 0; }');
    });
    if (rest.length) {
      out.push(eachRest('.cs-roster .cs-slot-' + first.id + ':hover .cs-slot-face') +
        ' { border: 1px solid ' + o.preview + '; box-shadow: 0 0 0 2px ' + o.ink + ', 6px 6px 0 #3158b8; }');
      out.push(eachRest('.cs-roster .cs-slot-' + first.id + ':hover .cs-slot-thumb') +
        ' { filter: saturate(.85) brightness(.92) contrast(1.08); }');
      out.push(eachRest('.cs-roster .cs-slot-' + first.id + ':hover .cs-stage-preview') + ',\n' +
        eachRest('.cs-roster .cs-slot-' + first.id + ':hover::after') + ' { opacity: 1; }');
    }
    out.push('');

    if (rest.length) {
      out.push('/* Stage art and copy for the open file. */');
      out.push(eachRest('.cs-scene .cs-art-' + first.id) + ' { opacity: 0; }');
      rest.forEach(function (f) {
        out.push(targeted(f, '.cs-scene .cs-art-' + f.id) + ' { opacity: 1; }');
      });
      rest.forEach(function (f) {
        out.push(targeted(f, '.cs-for-' + first.id) + ',\n' +
          targeted(f, '* .cs-for-' + first.id) + ' { display: none; }');
        out.push(targeted(f, '.cs-for-' + f.id) + ',\n' +
          targeted(f, '* .cs-for-' + f.id) + ' { display: block; }');
      });
      out.push('');
    }

    if (filters.length) {
      out.push('/* Tag filter. One hash at a time, so picking a character clears');
      out.push(' * the filter — which is the flow anyway: narrow, then choose. */');
      out.push('.cs-filter-all { border-color: ' + o.accent + '; background: ' + o.accent +
        '; color: ' + o.ink + ' !important; }');
      out.push(filters.map(function (t) {
        return '#f-' + t.key + ':target ~ .cs-roster .cs-filter-all';
      }).join(',\n') + ' { border-color: #3a403b; background: transparent; color: #9aa29b !important; }');
      filters.forEach(function (t) {
        out.push('#f-' + t.key + ':target ~ .cs-roster .cs-filter-' + t.key +
          ' { border-color: ' + o.accent + '; background: ' + o.accent + '; color: ' + o.ink + ' !important; }');
        out.push('#f-' + t.key + ':target ~ .cs-roster .cs-slot:not(.cs-t-' + t.key + ') { display: none; }');
      });
    }

    if (o.style === 'proxy-terminal') {
      out.push('');
      out.push('/* Pictures from Profile Information: friend faces and social icons. */');
      out.push('.zz-friend > span { overflow: hidden; }');
      out.push('.zz-friend > span img { display: block; width: 100%; height: 100%; object-fit: cover; object-position: center; }');
      out.push('.zz-social small { display: flex; align-items: center; gap: 9px; }');
      out.push('.zz-social-icon { display: block; width: 26px; height: 26px; border-radius: 6px; object-fit: cover; object-position: center; }');
    }

    return out.join('\n').replace(/\n{3,}/g, '\n\n').trim() + '\n';
  }

  // ------------------------------------------------------------- the splice

  /* Replaces the marked region, or appends a fresh one if there isn't one. */
  /* Takes a marked region out again, markers and all. */
  function removeBetween(text, start, end) {
    var from = text.indexOf(start);
    var to = text.indexOf(end);
    if (from === -1 || to < from) return text;
    return (text.slice(0, from) + text.slice(to + end.length)).replace(/\n{3,}/g, '\n\n');
  }

  function spliceBetween(text, start, end, body, joiner) {
    var from = text.indexOf(start);
    var to = text.indexOf(end);
    if (from !== -1 && to > from) {
      return text.slice(0, from + start.length) + joiner + body + joiner + text.slice(to);
    }
    return text + (text && !/\n$/.test(text) ? joiner : '') + start + joiner + body + joiner + end + joiner;
  }

  /*
   * Writes both halves into an About Me payload: the CSS into the last <style>
   * block, the markup after it. Idempotent — run it again after editing the
   * roster and only the marked regions change.
   */
  function apply(payload, roster, opts) {
    var o = options(opts);
    var styleCss = global.JaiHardcodeStyles ? global.JaiHardcodeStyles.css(o.style, o) : '';
    var generatedCss = css(roster, opts);
    var generatedHtml = markup(roster, opts);
    if (!generatedHtml) return payload;
    var text = payload || '';

    // Rewrite the block where it already is. JaiPayload.editCss always targets
    // the *last* <style>, which is the right answer for a new block and the
    // wrong one for a document whose markers sit in an earlier sheet — that
    // would leave the old block in place and quietly add a second.
    var host = null;
    global.JaiPayload.styleBlocks(text).forEach(function (block) {
      if (host === null && block.css.indexOf(CSS_START) !== -1) host = block;
    });
    // The chosen style's stylesheet goes in above the wiring, so the wiring's
    // state rules win over the look they decorate. Picking "none" takes it out
    // again rather than leaving an orphan block behind.
    function writeBoth(sheet) {
      var next = styleCss
        ? spliceBetween(sheet, STYLE_START, STYLE_END, styleCss, '\n')
        : removeBetween(sheet, STYLE_START, STYLE_END);
      return spliceBetween(next, CSS_START, CSS_END, generatedCss, '\n');
    }
    if (host) {
      text = text.slice(0, host.cssStart) + writeBoth(host.css) + text.slice(host.cssEnd);
    } else {
      text = global.JaiPayload.editCss(text, writeBoth);
    }
    return spliceBetween(text, HTML_START, HTML_END, generatedHtml, '\n');
  }

  /* Removes the generated card regions while leaving the creator's own CSS,
   * markup and surrounding style blocks untouched. Used when the last roster
   * item is deleted from the Cards panel. */
  function remove(payload) {
    var text = String(payload || '');
    var blocks = global.JaiPayload.styleBlocks(text);
    for (var i = blocks.length - 1; i >= 0; i--) {
      if (blocks[i].css.indexOf(CSS_START) === -1 && blocks[i].css.indexOf(STYLE_START) === -1) continue;
      var css = removeBetween(blocks[i].css, CSS_START, CSS_END);
      css = removeBetween(css, STYLE_START, STYLE_END);
      text = text.slice(0, blocks[i].cssStart) + css + text.slice(blocks[i].cssEnd);
    }
    return removeBetween(text, HTML_START, HTML_END);
  }

  function isApplied(payload) {
    return String(payload || '').indexOf(HTML_START) !== -1;
  }

  // ---------------------------------------------------------- card detection

  /*
   * Reads characters out of a captured profile. The capture is the real
   * JanitorAI DOM, so its own card classes are the source: name, description,
   * tag chips, the character link and the avatar all come off the card that
   * the site rendered. The avatar supplies both the tile portrait and centered,
   * clipped stage art by default; either can be overridden in the Cards panel.
   */
  function fromDocument(doc) {
    if (!doc) return [];
    var out = [];
    Array.prototype.forEach.call(doc.querySelectorAll('.pp-cc-wrapper'), function (card) {
      // The preview pads a short capture with copies of real cards so the grid
      // looks full; those are the same characters again, not new ones.
      if (card.hasAttribute('data-sim-card-copy')) return;
      var name = text(card.querySelector('.pp-cc-name'));
      if (!name) return;
      var link = card.querySelector('a[href*="/characters/"]') ||
        closest(card, 'a[href*="/characters/"]');
      var avatar = card.querySelector('.pp-cc-avatar img, img.pp-cc-avatar, .profile-character-card-avatar-image') ||
        card.querySelector('img');
      var avatarSrc = avatar && (avatar.getAttribute('data-jai-source-src') || avatar.getAttribute('src'));
      var defaultImage = usable(avatarSrc) ? avatarSrc : '';
      var tags = [];
      Array.prototype.forEach.call(card.querySelectorAll('.pp-cc-tags-item'), function (chip) {
        var tag = global.JaiTags.clean(text(chip));
        if (tag && tags.indexOf(tag) === -1) tags.push(tag);
      });
      out.push({
        name: name,
        description: text(card.querySelector('.pp-cc-description')),
        tags: tags,
        link: absolute(link && link.getAttribute('href')),
        portrait: defaultImage,
        art: defaultImage,
        hover: '',
        tagline: '',
        quote: '',
        chats: count(card.querySelector('.pp-cc-chats-count')),
        publicChats: count(card.querySelector('.pp-cc-public-chats-count')),
        tokens: count(card.querySelector('.pp-cc-tokens-count'))
      });
    });
    return out;
  }

  /* Counts render as the site writes them ("1.2k"); keep them that way. Only
   * the number and its own suffix: "1.8k tokens" has a second k in it. */
  function count(node) {
    var match = /[\d][\d.,]*\s*[kKmM]?/.exec(text(node));
    return match ? match[0].replace(/\s+/g, '') : '';
  }

  function text(node) { return node ? String(node.textContent || '').trim() : ''; }

  function closest(node, selector) {
    for (var el = node; el; el = el.parentElement) {
      if (el.matches && el.matches(selector)) return el;
    }
    return null;
  }

  /* A captured href is site-relative; the paste has to work from anywhere. */
  function absolute(href) {
    if (!href) return '';
    if (/^https?:/i.test(href)) return href;
    return 'https://janitorai.com' + (href.charAt(0) === '/' ? '' : '/') + href;
  }

  global.JaiHardcode = {
    markup: markup,
    usable: usable,
    css: css,
    apply: apply,
    remove: remove,
    isApplied: isApplied,
    fromDocument: fromDocument,
    filterTags: filterTags,
    prepare: prepare,
    slugify: slugify,
    defaults: DEFAULTS,
    markers: { htmlStart: HTML_START, htmlEnd: HTML_END, cssStart: CSS_START, cssEnd: CSS_END,
      styleStart: STYLE_START, styleEnd: STYLE_END }
  };
})(window);
