/* Generated by tools/build_reference.py — do not edit by hand.
 * Source: Puppy's JanitorAI Profile Page CSS Reference. */
window.JAI_REFERENCE = [
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Default Bot Card Layer 1 (overall container)",
  "labels": [
   ".pp-cc-wrapper",
   ".profile-character-card-wrapper"
  ],
  "ids": [
   ".css-13wmn96"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Background Layer 1",
  "labels": [
   ".pp-cc-gradient-1"
  ],
  "ids": [
   ".css-13wmn96>.css-0"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Background Layer 2",
  "labels": [
   ".pp-cc-gradient-2"
  ],
  "ids": [
   ".css-dltla"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Background Layer 3",
  "labels": [
   ".pp-cc-gradient-3"
  ],
  "ids": [
   ".css-1jf56se"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Main bot card info container",
  "labels": [
   ".profile-character-card-stack"
  ],
  "ids": [
   ".css-1s5evre"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Bot link (contains name, chat ribbon, bot image)",
  "labels": [
   ".profile-character-card-stack-link-component"
  ],
  "ids": [
   ".css-1s5evre a:nth-child(1)"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Bot name container",
  "labels": [
   ".profile-character-card-stack-link-component-box"
  ],
  "ids": [
   ".css-nlxhw4"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Bot name text",
  "labels": [
   ".pp-cc-name",
   ".profile-character-card-name-box"
  ],
  "ids": [
   ".css-nlxhw4>div"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Chat ribbon main container",
  "labels": [
   ".profile-character-card-stats-box"
  ],
  "ids": [
   ".css-10cv7r2"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Chat ribbon first span (purpose unknown)",
  "labels": [],
  "ids": [
   ".css-10cv7r2>.css-1baulvz"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Chat ribbon outer container (drop shadow + positioning)",
  "labels": [
   ".pp-cc-ribbon",
   ".profile-character-card-ribbon"
  ],
  "ids": [
   "._ribbon_67d1x_1",
   ".css-1ket5wn"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Chat ribbon shape (background, box-shadow, clip-path)",
  "labels": [
   ".pp-cc-ribbon-wrap",
   ".profile-character-card-ribbon-wrap"
  ],
  "ids": [
   "._content_67d1x_11",
   ".css-wexxj8"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Chat ribbon text container (count + icon)",
  "labels": [
   ".pp-cc-chats",
   ".profile-character-card-chats-hstack"
  ],
  "ids": [
   ".css-euh5x6"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Chat ribbon icon",
  "labels": [
   ".pp-cc-chats svg"
  ],
  "ids": [
   ".css-euh5x6 svg"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Chat ribbon number",
  "labels": [
   ".pp-cc-chats-count",
   ".profile-character-card-chats-count"
  ],
  "ids": [
   ".css-euh5x6 span"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Public chat count",
  "labels": [
   ".pp-cc-public-chats",
   ".profile-character-card-public-chats-hstack"
  ],
  "ids": [
   ".css-y395z1"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Public chat count icon",
  "labels": [
   ".pp-cc-public-chats svg"
  ],
  "ids": [
   ".css-y395z1 svg"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Bot image container",
  "labels": [
   ".profile-character-card-avatar-aspect-ratio"
  ],
  "ids": [
   ".css-1q7rmf0"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Bot image",
  "labels": [
   ".pp-cc-avatar",
   ".profile-character-card-avatar-image"
  ],
  "ids": [
   ".css-1q7rmf0 img"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Username on bot card",
  "labels": [
   ".profile-character-card-creator-name-link"
  ],
  "ids": [
   ".css-1s5evre a:nth-child(2)"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Username on bot card (text)",
  "labels": [
   ".pp-cc-creator-name",
   ".profile-character-card-creator-name-box"
  ],
  "ids": [
   ".css-1s5evre a:nth-child(2) span"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Description container",
  "labels": [
   ".profile-character-card-description-box"
  ],
  "ids": [
   ".css-199gcrh"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Description paragraph container",
  "labels": [
   ".pp-cc-description",
   ".profile-character-card-description-markdown-container"
  ],
  "ids": [
   ".css-96l1id"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Description paragraph text",
  "labels": [
   ".pp-cc-description p",
   ".profile-character-card-description-markdown-container p"
  ],
  "ids": [
   ".css-96l1id p",
   ".css-199gcrh p"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Star line separator",
  "labels": [
   ".pp-cc-star-line",
   ".profile-character-card-star-line"
  ],
  "ids": [
   ".css-1s5evre>div:nth-child(4)",
   ".css-1lgnt2x"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Star image",
  "labels": [
   ".pp-cc-star",
   ".profile-character-card-star"
  ],
  "ids": [
   ".css-1s5evre>div:nth-child(4) img",
   ".css-1lgnt2x img"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Tags container",
  "labels": [
   ".pp-cc-tags",
   ".profile-character-card-tags"
  ],
  "ids": [
   ".css-4ofde4"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Tags list container",
  "labels": [],
  "ids": [
   ".css-k1urot"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Limitless tag container",
  "labels": [
   ".pp-cc-tags-wrap",
   ".profile-character-card-tags-wrap"
  ],
  "ids": [
   ".css-123m5uu"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Limitless tag styling",
  "labels": [
   ".pp-tag-limitless",
   ".profile-character-card-tag-limitless"
  ],
  "ids": [
   ".css-123m5uu span"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "All other tags (excluding custom tags)",
  "labels": [
   ".pp-cc-tags-wrap-regular",
   ".profile-character-card-tags-wrap",
   ".profile-character-card-tags-wrap-regular"
  ],
  "ids": [
   ".css-k1urot>.css-1yp4ln"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Tag styling",
  "labels": [
   ".pp-cc-tags-item",
   ".pp-cc-tags-regular",
   ".pp-tag-[nameoftag]"
  ],
  "ids": [
   ".css-k1urot span"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Custom tag styling",
  "labels": [
   ".pp-cc-tags-custom and .pp-tag-[customhere]"
  ],
  "ids": [
   ".pp-cc-tags-wrap-custom span"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Token count container",
  "labels": [
   ".profile-character-card-box"
  ],
  "ids": [
   ".css-1c9wmts"
  ]
 },
 {
  "group": "Default Bot Card Elements",
  "sub": "",
  "element": "Token count text",
  "labels": [
   ".pp-cc-tokens-count",
   ".profile-character-card-tokens-count"
  ],
  "ids": [
   ".css-1c9wmts p"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Bot Card Layer 1 (overall container)",
  "labels": [
   ".pp-cc-wrapper"
  ],
  "ids": [
   ".css-mwqlii"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Background Layer 1",
  "labels": [
   ".pp-cc-gradient-1"
  ],
  "ids": [
   ".css-mwqlii>.css-0"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Background Layer 2",
  "labels": [
   ".pp-cc-gradient-2"
  ],
  "ids": [
   ".css-dltla"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Background Layer 3",
  "labels": [
   ".pp-cc-gradient-3"
  ],
  "ids": [
   ".css-1x9vwxq"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Background Layer 4",
  "labels": [],
  "ids": [
   ".css-4bfvm5"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Background Layer 5",
  "labels": [],
  "ids": [
   ".css-1xjyfw9"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Bot name text",
  "labels": [
   ".pp-cc-name"
  ],
  "ids": [
   ".css-1i5dnvi"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Username link container",
  "labels": [
   ".profile-character-card-creator-name-link"
  ],
  "ids": [
   ".css-1xhci6i"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Star line separator",
  "labels": [
   ".pp-cc-star-line"
  ],
  "ids": [
   ".css-u4e2i0"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Star image",
  "labels": [
   ".pp-cc-star"
  ],
  "ids": [
   ".css-17uwqlj"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Flower container",
  "labels": [],
  "ids": [
   ".css-8828od"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Flower emoji",
  "labels": [],
  "ids": [
   ".css-itvw0n"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Extra Border Layer 1",
  "labels": [],
  "ids": [
   ".css-y7b0z0"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Spring Fever 2026",
  "element": "Extra Border Layer 2",
  "labels": [],
  "ids": [
   ".css-yhe1df"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2026 (#TheValentine)",
  "element": "Bot Card Layer 1 (overall container)",
  "labels": [
   ".pp-cc-wrapper"
  ],
  "ids": [
   ".css-1idbk73"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2026 (#TheValentine)",
  "element": "Background Layer 1",
  "labels": [
   ".pp-cc-gradient-1"
  ],
  "ids": [
   ".css-1idbk73>.css-0"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2026 (#TheValentine)",
  "element": "Background Layer 2",
  "labels": [
   ".pp-cc-gradient-2"
  ],
  "ids": [
   ".css-dltla"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2026 (#TheValentine)",
  "element": "Background Layer 3",
  "labels": [
   ".pp-cc-gradient-3"
  ],
  "ids": [
   ".css-sfkyc4"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2026 (#TheValentine)",
  "element": "Background Layer 4",
  "labels": [],
  "ids": [
   ".css-d1itua"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2026 (#TheValentine)",
  "element": "Background Layer 5",
  "labels": [],
  "ids": [
   ".css-bfvnvu"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2026 (#TheValentine)",
  "element": "Background Layer 6",
  "labels": [],
  "ids": [
   ".css-16qjfxm"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2026 (#TheValentine)",
  "element": "Bot name text",
  "labels": [
   ".pp-cc-name"
  ],
  "ids": [
   ".css-1ani293"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2026 (#TheValentine)",
  "element": "Username link container",
  "labels": [],
  "ids": [
   ".css-16f51li"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2026 (#TheValentine)",
  "element": "Star line separator",
  "labels": [
   ".pp-cc-star-line"
  ],
  "ids": [
   ".css-gc4bc9"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2026 (#TheValentine)",
  "element": "Star image",
  "labels": [
   ".pp-cc-star"
  ],
  "ids": [
   ".css-ovzirr"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Bot Card Layer 1 (overall container)",
  "labels": [
   ".pp-cc-wrapper"
  ],
  "ids": [
   ".css-1mrg1rp"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Background Layer 1",
  "labels": [
   ".pp-cc-gradient-1"
  ],
  "ids": [
   ".css-1mrg1rp>.css-0"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Background Layer 2",
  "labels": [
   ".pp-cc-gradient-2"
  ],
  "ids": [
   ".css-dltla"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Background Layer 3",
  "labels": [
   ".pp-cc-gradient-3"
  ],
  "ids": [
   ".css-sfkyc4"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Background Layer 4",
  "labels": [],
  "ids": [
   ".css-1ifqy49"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Background Layer 5",
  "labels": [],
  "ids": [
   ".css-1drof3r"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Bot name text",
  "labels": [
   ".pp-cc-name"
  ],
  "ids": [
   ".css-1on0xzz"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Username link container",
  "labels": [],
  "ids": [
   ".css-16f51li"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Star line separator",
  "labels": [
   ".pp-cc-star-line"
  ],
  "ids": [
   ".css-1pjvf4r"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Star image",
  "labels": [
   ".pp-cc-star"
  ],
  "ids": [
   ".css-1h8fads"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Hamster container",
  "labels": [],
  "ids": [
   ".css-5v5qgx"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Valentine's 2025 (retired)",
  "element": "Hamster image",
  "labels": [],
  "ids": [
   ".css-5v5qgx img"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "New Year 2025",
  "element": "Bot Card Layer 1 (overall container)",
  "labels": [
   ".pp-cc-wrapper"
  ],
  "ids": [
   ".css-1udesvb"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "New Year 2025",
  "element": "Background Layer 1",
  "labels": [
   ".pp-cc-gradient-1"
  ],
  "ids": [
   ".css-1udesvb>.css-0"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "New Year 2025",
  "element": "Background Layer 2",
  "labels": [
   ".pp-cc-gradient-2"
  ],
  "ids": [
   ".css-dltla"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "New Year 2025",
  "element": "Background Layer 3",
  "labels": [
   ".pp-cc-gradient-3"
  ],
  "ids": [
   ".css-1nf28v0"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "New Year 2025",
  "element": "Background Layer 4",
  "labels": [],
  "ids": [
   ".css-gum7ka"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "New Year 2025",
  "element": "Background Layer 5",
  "labels": [],
  "ids": [
   ".css-ke8k8l"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "New Year 2025",
  "element": "Bot name text",
  "labels": [
   ".pp-cc-name"
  ],
  "ids": [
   ".css-kesdt6"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "New Year 2025",
  "element": "Username link container",
  "labels": [],
  "ids": [
   ".css-vquwtv"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "New Year 2025",
  "element": "Star line separator",
  "labels": [
   ".pp-cc-star-line"
  ],
  "ids": [
   ".css-nackew"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "New Year 2025",
  "element": "Star image",
  "labels": [
   ".pp-cc-star"
  ],
  "ids": [
   ".css-ee63sa"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "New Year 2025",
  "element": "2025 stamp",
  "labels": [],
  "ids": [
   ".css-1wqmh16"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Halloween",
  "element": "Bot Card Layer 1 (overall container)",
  "labels": [
   ".pp-cc-wrapper"
  ],
  "ids": [
   ".css-13wmn96:has(.css-nip9dx)"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Halloween",
  "element": "Background Layer 1",
  "labels": [
   ".pp-cc-gradient-1"
  ],
  "ids": [
   ".css-13wmn96:has(.css-nip9dx)>.css-0"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Halloween",
  "element": "Background Layer 2",
  "labels": [
   ".pp-cc-gradient-2"
  ],
  "ids": [
   ".css-dltla"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Halloween",
  "element": "Background Layer 3",
  "labels": [
   ".pp-cc-gradient-3"
  ],
  "ids": [
   ".css-1xy4dr7"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Halloween",
  "element": "Bot name text",
  "labels": [
   ".pp-cc-name"
  ],
  "ids": [
   ".css-7l95y2"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Halloween",
  "element": "Username link container",
  "labels": [],
  "ids": [
   ".css-1yeq7x5"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Halloween",
  "element": "Star line separator",
  "labels": [
   ".pp-cc-star-line"
  ],
  "ids": [
   ".css-1ov83hg"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Halloween",
  "element": "Star image",
  "labels": [
   ".pp-cc-star"
  ],
  "ids": [
   ".css-w470et"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Halloween",
  "element": "Pumpkin container",
  "labels": [],
  "ids": [
   ".css-nip9dx"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Halloween",
  "element": "Pumpkin image",
  "labels": [],
  "ids": [
   ".css-nip9dx img"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Christmas",
  "element": "Bot Card Layer 1 (overall container)",
  "labels": [
   ".pp-cc-wrapper"
  ],
  "ids": [
   ".css-1hyhy7j"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Christmas",
  "element": "Background Layer 1",
  "labels": [
   ".pp-cc-gradient-1"
  ],
  "ids": [
   ".css-1hyhy7j>.css-0"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Christmas",
  "element": "Background Layer 2",
  "labels": [
   ".pp-cc-gradient-2"
  ],
  "ids": [
   ".css-dltla"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Christmas",
  "element": "Background Layer 3",
  "labels": [
   ".pp-cc-gradient-3"
  ],
  "ids": [
   ".css-ievdy4"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Christmas",
  "element": "Bot name text",
  "labels": [
   ".pp-cc-name"
  ],
  "ids": [
   ".css-6pkpcc"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Christmas",
  "element": "Username link container",
  "labels": [],
  "ids": [
   ".css-9pz3h"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Christmas",
  "element": "Star line separator",
  "labels": [
   ".pp-cc-star-line"
  ],
  "ids": [
   ".css-xr5j9y"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Christmas",
  "element": "Star image",
  "labels": [
   ".pp-cc-star"
  ],
  "ids": [
   ".css-7rspww"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Christmas",
  "element": "Christmas lights container",
  "labels": [],
  "ids": [
   ".css-xrg4vd"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Christmas",
  "element": "Christmas lights image",
  "labels": [],
  "ids": [
   ".css-xrg4vd img"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Bot Card Layer 1 (overall container)",
  "labels": [
   ".pp-cc-wrapper"
  ],
  "ids": [
   ".css-y0anzw"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Background Layer 1",
  "labels": [
   ".pp-cc-gradient-1"
  ],
  "ids": [
   ".css-y0anzw>.css-0"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Background Layer 2",
  "labels": [
   ".pp-cc-gradient-2"
  ],
  "ids": [
   ".css-dltla"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Background Layer 3",
  "labels": [
   ".pp-cc-gradient-3"
  ],
  "ids": [
   ".css-1vbkq2z"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Background Layer 4",
  "labels": [],
  "ids": [
   ".css-14hnweu"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Background Layer 5",
  "labels": [],
  "ids": [
   ".css-obdrgl"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Background Layer 6",
  "labels": [],
  "ids": [
   ".css-gcl0iy"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Bot name text",
  "labels": [
   ".pp-cc-name"
  ],
  "ids": [
   ".css-vk0mim"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Username link container",
  "labels": [],
  "ids": [
   ".css-due2rz"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Star line separator",
  "labels": [
   ".pp-cc-star-line"
  ],
  "ids": [
   ".css-z6f8pk"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Star image",
  "labels": [
   ".pp-cc-star"
  ],
  "ids": [
   ".css-17nmj64"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Palm tree emoji",
  "labels": [],
  "ids": [
   ".css-1awld45"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Passport To Pages",
  "element": "Conch shell emoji",
  "labels": [],
  "ids": [
   ".css-1cui3us"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Bot Card Layer 1 (overall container)",
  "labels": [
   ".pp-cc-wrapper"
  ],
  "ids": [
   ".css-1ej831h"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Background Layer 1",
  "labels": [
   ".pp-cc-gradient-1"
  ],
  "ids": [
   ".css-1ej831h>.css-0"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Background Layer 2",
  "labels": [
   ".pp-cc-gradient-2"
  ],
  "ids": [
   ".css-dltla"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Background Layer 3",
  "labels": [
   ".pp-cc-gradient-3"
  ],
  "ids": [
   ".css-111nr3m"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Background Layer 4",
  "labels": [],
  "ids": [
   ".css-w89cv5"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Background Layer 5",
  "labels": [],
  "ids": [
   ".css-1utqofo"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Bot name text",
  "labels": [
   ".pp-cc-name"
  ],
  "ids": [
   ".css-d3yj25"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Username link container",
  "labels": [
   ".profile-character-card-creator-name-link"
  ],
  "ids": [
   ".css-9yp4xs"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Star line separator",
  "labels": [
   ".pp-cc-star-line"
  ],
  "ids": [
   ".css-17mt2nc"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Star image",
  "labels": [
   ".pp-cc-star"
  ],
  "ids": [
   ".css-14orm77"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Snowflake container",
  "labels": [],
  "ids": [
   ".css-8828od"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Snowflake SVG",
  "labels": [],
  "ids": [
   ".css-8828od svg"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Extra Border Layer 1",
  "labels": [],
  "ids": [
   ".css-1henxb"
  ]
 },
 {
  "group": "Event-Specific Bot Card Elements",
  "sub": "Holidays 2025",
  "element": "Extra Border Layer 2",
  "labels": [],
  "ids": [
   ".css-effh3d"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Main / General Page Elements",
  "element": "Body",
  "labels": [
   "body"
  ],
  "ids": []
 },
 {
  "group": "Profile Page Elements",
  "sub": "Main / General Page Elements",
  "element": "Root",
  "labels": [
   "root"
  ],
  "ids": []
 },
 {
  "group": "Profile Page Elements",
  "sub": "Main / General Page Elements",
  "element": "Page flex container",
  "labels": [],
  "ids": [
   "._wrapper_13xo6_1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Main / General Page Elements",
  "element": "Header container",
  "labels": [
   ".profile-top-bar-flex-outer",
   ".pp-top-bar-outer"
  ],
  "ids": [
   "._header_1lgb1_1",
   "header"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Main / General Page Elements",
  "element": "Profile main parent container (side padding)",
  "labels": [
   "._customPadding_qqqm3_15"
  ],
  "ids": [
   "._main_qqqm3_1",
   "main"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Main / General Page Elements",
  "element": "Profile wrapper container (top padding)",
  "labels": [
   ".profile-page-container"
  ],
  "ids": [
   ".css-14l6kwv"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Main / General Page Elements",
  "element": "Profile background (holds background image if set)",
  "labels": [
   ".pp-page-background",
   ".profile-page-background"
  ],
  "ids": [
   "UNIQUE"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Main / General Page Elements",
  "element": "Profile / bot card flex parent container",
  "labels": [
   ".profile-page-flex"
  ],
  "ids": [
   ".css-1wfbrwg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Main / General Page Elements",
  "element": "Footer container",
  "labels": [
   "footer"
  ],
  "ids": [
   "._footer_b4zg4_1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Profile box layer 1 (main container)",
  "labels": [
   ".pp-uc-background",
   ".profile-uc-background-flex"
  ],
  "ids": [
   ".css-1wfbrwg>div:nth-child(1)",
   ".css-vqimyu"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Background layer 1",
  "labels": [
   ".profile-background-box-1"
  ],
  "ids": [
   ".css-1wfbrwg>div:nth-child(1)>.css-0"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Background layer 2",
  "labels": [
   ".profile-background-box-2"
  ],
  "ids": [
   ".css-1wfbrwg>div:nth-child(1)>div:nth-child(2)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Background layer 3",
  "labels": [
   ".profile-background-box-3"
  ],
  "ids": [
   ".css-1wfbrwg>div:nth-child(1)>div:nth-child(3)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Profile box inner container",
  "labels": [
   ".profile-info-wrapper-box"
  ],
  "ids": [
   ".css-1wfbrwg>div:nth-child(1)>div:nth-child(4)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Profile box inner stack (orders user info, bio, follow/options buttons)",
  "labels": [
   ".profile-info-stack"
  ],
  "ids": [
   ".css-1wfbrwg>div:nth-child(1)>div>.css-8g8ihq"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "User info main container (PFP, username, followers, badges, join date)",
  "labels": [
   ".profile-info-hstack"
  ],
  "ids": [
   ".css-1uodvt1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Profile image container",
  "labels": [
   ".pp-uc-avatar-container",
   ".profile-avatar-container"
  ],
  "ids": [
   ".css-79elbk"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Profile image",
  "labels": [
   ".pp-uc-avatar",
   ".profile-avatar"
  ],
  "ids": [
   ".css-18bnokj",
   ".css-79elbk img"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "User info container (everything except the PFP)",
  "labels": [
   ".profile-info-stack-inner"
  ],
  "ids": [
   ".css-1uodvt1>.css-8g8ihq"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Username container",
  "labels": [
   ".profile-info-stack-inner-flex"
  ],
  "ids": [
   ".css-70qvj9",
   ".css-1uodvt1>.css-8g8ihq>div:nth-child(1)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Username",
  "labels": [
   ".pp-uc-title",
   ".profile-title-heading"
  ],
  "ids": [
   ".css-70qvj9 h2",
   ".css-o5an2m",
   ".css-1uodvt1>.css-8g8ihq>div:nth-child(1) h2"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Verification badge container",
  "labels": [
   ".profile-verified-box"
  ],
  "ids": [
   ".css-17c2y77"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Verification badge",
  "labels": [
   ".profile-verified-mark"
  ],
  "ids": [
   ".css-xeged3"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Verification badge icon",
  "labels": [
   ".profile-verified-mark svg"
  ],
  "ids": [
   ".css-xeged3 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "JanitorAI+ badge container",
  "labels": [
   ".profile-janitor-plus-box"
  ],
  "ids": [
   ".css-17c2y77"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "JanitorAI+ badge inner container",
  "labels": [
   ".profile-janitor-plus-box>span"
  ],
  "ids": [
   "._root_l8p4e_1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "JanitorAI+ badge",
  "labels": [
   "span[aria-label=\"janitor+ Subscriber\"]"
  ],
  "ids": [
   "._wrapperPaired_1tafp_3"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "JanitorAI+ badge icon",
  "labels": [
   "[aria-label=\"janitor+ Subscriber\"] svg"
  ],
  "ids": [
   "._wrapperPaired_1tafp_3 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "JanitorAI+ badge tooltip",
  "labels": [
   ".profile-janitor-plus-box span[role=\"tooltip\"]"
  ],
  "ids": [
   "._popup_l8p4e_7"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "JanitorAI+ badge tooltip contents",
  "labels": [
   ".profile-janitor-plus-box span[role=\"tooltip\"] svg"
  ],
  "ids": [
   "._popup_l8p4e_7 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Moderator badge container",
  "labels": [],
  "ids": [
   ".css-8amxhq"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Moderator badge",
  "labels": [],
  "ids": [
   ".css-8amxhq img"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Followers count container",
  "labels": [
   ".pp-uc-followers-count",
   ".profile-followers-count"
  ],
  "ids": [
   ".css-1uodvt1>.css-8g8ihq>div:nth-child(2)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Followers number",
  "labels": [
   ".pp-uc-followers-count span:nth-of-type(1)"
  ],
  "ids": [
   ".css-1uodvt1>.css-8g8ihq>div:nth-child(2) span:nth-of-type(1)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Followers text",
  "labels": [
   ".pp-uc-followers-count span:nth-of-type(2)"
  ],
  "ids": [
   ".css-1uodvt1>.css-8g8ihq>div:nth-child(2) span:nth-of-type(2)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Event badge container",
  "labels": [
   ".profile-badges"
  ],
  "ids": [
   ".css-1n7vfh0",
   ".css-1uodvt1>.css-8g8ihq>div:nth-child(3)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Event badges (non-specific)",
  "labels": [
   ".profile-badge"
  ],
  "ids": [
   ".css-x3wokz"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Event badge image (non-specific)",
  "labels": [
   ".profile-badge-img"
  ],
  "ids": [
   ".css-1x0d536"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Member since / date joined",
  "labels": [
   ".pp-uc-member-since",
   ".profile-member-since-box"
  ],
  "ids": [
   ".css-1uodvt1>.css-8g8ihq>div:nth-child(4)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Profile bio main container",
  "labels": [
   ".pp-uc-about-me",
   ".profile-about-me"
  ],
  "ids": [
   ".css-1bn1yyx"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Follow / Options button main container",
  "labels": [
   ".pp-uc-about-me + div",
   ".pp-uc-about-me + *"
  ],
  "ids": [
   "div:has(>.css-1aq5geu)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Follow / Options flex container",
  "labels": [
   "div:has(>.profile-uc-follow-flex)"
  ],
  "ids": [
   ".css-1aq5geu"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Follow button main container",
  "labels": [
   ".profile-uc-follow-flex"
  ],
  "ids": [
   ".css-1aq5geu>div:nth-child(1)",
   ".css-1vakbk4"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Follow button outer styling (border)",
  "labels": [
   ".pp-uc-follow-button",
   ".profile-uc-follow-button"
  ],
  "ids": [
   ".Btn"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Follow button inner styling (background)",
  "labels": [
   ".pp-uc-follow-button:before",
   ".profile-uc-follow-button:before"
  ],
  "ids": [
   ".Btn:before"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Follow button text",
  "labels": [
   ".profile-uc-follow-text"
  ],
  "ids": [
   ".Btn span"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Options button main container",
  "labels": [
   ".pp-uc-options-menu",
   ".chakra-menu__menu-button"
  ],
  "ids": [
   ".css-15w88gn"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Options button text",
  "labels": [],
  "ids": [
   ".css-15w88gn>span:nth-child(1)",
   ".css-xl71ch"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Options button 3-dots container",
  "labels": [],
  "ids": [
   ".css-15w88gn>span:nth-child(2)",
   ".css-1hzyiq5"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Profile Box",
  "element": "Options button 3 dots",
  "labels": [
   ".pp-uc-options-menu svg"
  ],
  "ids": [
   ".css-1hzyiq5 svg",
   ".css-15w88gn svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Header flex container",
  "labels": [],
  "ids": [
   "._wrapper_13xo6_1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Header parent container",
  "labels": [
   ".profile-top-bar-flex-outer",
   ".pp-top-bar-outer"
  ],
  "ids": [
   "._header_17iy7_1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Header inner flex container (holds sub-containers 1 & 2)",
  "labels": [
   ".pp-top-bar",
   ".profile-top-bar",
   ".pp-top-bar-inner"
  ],
  "ids": [
   "._bar_17iy7_26"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Header sub-container 1 (JAI beta logo + search bar)",
  "labels": [
   ".profile-top-box-flex-inner",
   ".pp-top-bar-left"
  ],
  "ids": [
   "._left_17iy7_45"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "JAI logo main flex container",
  "labels": [
   ".profile-top-bar-logo-box (label shared with link container below)"
  ],
  "ids": [
   "._logoContainer_17iy7_7"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "JAI logo flex container",
  "labels": [
   ".profile-top-bar-logo-box>div"
  ],
  "ids": [
   ".css-3v84gn"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "JAI logo main link container",
  "labels": [
   "a.profile-top-bar-logo-box"
  ],
  "ids": [
   ".css-99y9bx"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "JAI logo container (background, box-shadow, text-shadow, backdrop-filter)",
  "labels": [
   ".pp-top-bar-logo",
   ".profile-top-bar-logo"
  ],
  "ids": [
   ".glow-logo",
   ".css-1bmggo3"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "\"Janitor\" text portion",
  "labels": [
   ".pp-top-bar-logo-name",
   ".profile-top-bar-logo-name"
  ],
  "ids": [
   ".glow-logo h2"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "\"Beta\" text portion",
  "labels": [
   ".pp-top-bar-logo-sub-name",
   ".profile-top-bar-logo-sub-name"
  ],
  "ids": [
   ".glow-logo p"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Empty space between logo and search bar (yes, it's an element)",
  "labels": [
   ".profile-top-box-search-input-spacer-top"
  ],
  "ids": [
   "._spacer_17iy7_59"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Search bar main flex container",
  "labels": [
   ".profile-top-bar-search-wrapper"
  ],
  "ids": [
   "._searchInputContainer_17iy7_19"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Search bar main container",
  "labels": [
   ".profile-top-bar-search-box",
   ".pp-top-bar-search-box"
  ],
  "ids": [
   "._container_fgb7n_1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Search bar form",
  "labels": [
   ".pp-top-bar-search-form"
  ],
  "ids": [
   "._form_o5odd_129"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Search bar secondary container",
  "labels": [
   ".profile-top-bar-search-input-group",
   ".pp-top-bar-search-input-group"
  ],
  "ids": [
   "._inputGroup_o5odd_1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Magnifying glass container",
  "labels": [
   ".pp-top-bar-search-icon"
  ],
  "ids": [
   "._leftElement_o5odd_8"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Magnifying glass sub-container",
  "labels": [],
  "ids": [
   "._searchIcon_o5odd_21"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Magnifying glass icon",
  "labels": [
   ".pp-top-bar-search-icon svg"
  ],
  "ids": [
   "._searchIcon_o5odd_21 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Search bar background",
  "labels": [
   ".pp-top-bar-search",
   ".profile-top-bar-search",
   ".search-input",
   ".pp-top-bar-search-input"
  ],
  "ids": [
   "._inputContainer_1d69i_26"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Search bar placeholder text",
  "labels": [
   "#search-input"
  ],
  "ids": [
   "#search-input"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Search history parent container",
  "labels": [
   ".pp-top-bar-search-history"
  ],
  "ids": [
   "._dropdown_o5odd_108"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Individual history item container",
  "labels": [
   ".pp-top-bar-search-history>div",
   "[class*=\"historyItem_\"]"
  ],
  "ids": [
   "._historyItem_10txd_1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "History item outer text container",
  "labels": [
   "[class*=\"contentSection_\"]"
  ],
  "ids": [
   "._contentSection_10txd_53"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Clock icon container",
  "labels": [
   "[class*=\"iconWrapper_\"]"
  ],
  "ids": [
   "._iconWrapper_dg9q2_61"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Clock icon SVG",
  "labels": [
   "[class*=\"iconWrapper_\"] svg"
  ],
  "ids": [
   "._iconWrapper_dg9q2_61 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "History item separator",
  "labels": [],
  "ids": [
   "._historyItem_dg9q2_1:after"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "History item text",
  "labels": [
   "[class*=\"queryText_\"]"
  ],
  "ids": [
   "._queryText_10txd_67"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Remove-from-history button",
  "labels": [
   "[class*=\"removeButton_\"]"
  ],
  "ids": [
   "._removeButton_10txd_79"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Remove-from-history X SVG",
  "labels": [
   "[class*=\"removeButton_\"] svg"
  ],
  "ids": [
   "._removeButton_dg9q2_79 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Small space at end of search bar",
  "labels": [
   ".pp-top-bar-search-right"
  ],
  "ids": [
   "._rightElement_o5odd_67"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Empty space between search bar and create character button",
  "labels": [
   ".profile-top-box-search-input-spacer-bottom"
  ],
  "ids": [
   "._spacer_17iy7_59:nth-of-type(2)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Header sub-container 2 (create character, notifications, user button)",
  "labels": [
   ".pp-top-bar-right"
  ],
  "ids": [
   "._right_17iy7_53"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Header sub-container 2 inner flex",
  "labels": [],
  "ids": [
   "._container_1jb5k_1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Create character button",
  "labels": [
   ".pp-top-bar-create-char",
   ".profile-top-bar-create-char"
  ],
  "ids": [
   "._createButton_1jb5k_14",
   ".glow-on-hover"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Create character button on hover (the purple)",
  "labels": [
   ".pp-top-bar-create-char:before",
   ".profile-top-bar-create-char:before"
  ],
  "ids": [
   ".glow-on-hover:before"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Create character button hover background layer (the grey)",
  "labels": [
   ".pp-top-bar-create-char:after",
   ".profile-top-bar-create-char:after"
  ],
  "ids": [
   ".glow-on-hover:after"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Notifications outer button container",
  "labels": [
   ".pp-top-bar-notifications",
   ".profile-top-bar-notifications"
  ],
  "ids": [
   "._notificationsContainer_1jwi8_"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Notifications button container",
  "labels": [
   "[aria-label=\"Notifications\"]",
   ".pp-top-bar-notifications-button"
  ],
  "ids": [
   "._notificationsButton_1jwi8_7"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Notification bell",
  "labels": [
   ".pp-top-bar-notifications-button svg"
  ],
  "ids": [
   "._notificationsButton_1jwi8_7 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "Unread notification circle",
  "labels": [
   ".pp-top-bar-notifications-badge"
  ],
  "ids": [
   "._notificationsBadge_1jwi8_41"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "User icon container",
  "labels": [
   ".pp-top-bar-app-menu",
   ".profile-top-bar-app-menu"
  ],
  "ids": [
   ".css-rvct59"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "User icon secondary container",
  "labels": [],
  "ids": [
   ".css-rvct59>.css-xl71ch"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "User icon transition layer",
  "labels": [],
  "ids": [
   ".css-2jhocq"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "User icon flex layer",
  "labels": [
   "[class*=\"_avatarWrap_\"]"
  ],
  "ids": [
   "._avatarWrap_1xv0r_3"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "User icon image container",
  "labels": [],
  "ids": [
   ".css-fsfp0u"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Desktop Header",
  "element": "User icon image",
  "labels": [],
  "ids": [
   ".css-fsfp0u img"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Main container (tabs, character count, search, filter, latest menu, card grid)",
  "labels": [
   ".profile-page-container-flex-box"
  ],
  "ids": [
   ".css-1wfbrwg>div:nth-child(2)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Characters/Chats/Scripts tab main container",
  "labels": [
   ".profile-tabs-chakra-tabs",
   "#profile-tabs"
  ],
  "ids": [
   ".css-1bx5ylf"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Tab button container",
  "labels": [
   ".pp-tabs-wrapper",
   ".profile-tabs-wrapper"
  ],
  "ids": [
   ".css-i3ef4m"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Tab button background & text container",
  "labels": [
   ".pp-tabs-button",
   ".profile-tabs-button"
  ],
  "ids": [
   ".css-1nrqjj0"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "'Characters' tab button",
  "labels": [
   "button[data-tab=\"characters\"]"
  ],
  "ids": []
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "'Chats' tab button",
  "labels": [
   "button[data-tab=\"chats\"]"
  ],
  "ids": []
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "'Scripts' tab button",
  "labels": [
   "button[data-tab=\"scripts\"]"
  ],
  "ids": []
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Tab button glowing bar",
  "labels": [
   ".pp-tabs-indicator",
   ".profile-tabs-indicator"
  ],
  "ids": [
   ".css-h3ayx3"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character page container layer 2",
  "labels": [
   ".pp-tabs-panels",
   ".profile-tabs-panels"
  ],
  "ids": [
   ".css-1bx5ylf>div:nth-child(2)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character page container layer 3",
  "labels": [
   ".profile-tab-panel"
  ],
  "ids": [
   ".css-1bx5ylf>div:nth-child(2)>div"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character page container layer 4",
  "labels": [],
  "ids": [
   ".css-2n7zf2"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character page flexbox (holds sub-containers 1–3)",
  "labels": [
   ".characters-list-container-flex"
  ],
  "ids": [
   ".css-2n7zf2>div"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Sub-container 1 (character count, search, filter, latest menu)",
  "labels": [
   ".character-list-pagination-flex"
  ],
  "ids": [
   ".css-2n7zf2>div>div:nth-child(1)",
   ".css-m8ywhg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character count main container",
  "labels": [
   ".character-list-pagination-box"
  ],
  "ids": [
   ".css-6su6fj",
   ".css-m8ywhg>div:nth-child(1)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character count flex layer",
  "labels": [
   ".profile-pagination-flex-outer"
  ],
  "ids": [
   ".css-1pfxi6a"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character count styling (border)",
  "labels": [
   ".pp-pg-total",
   ".profile-badge-flex-outer"
  ],
  "ids": [
   ".Btn2-purple"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character count styling (background)",
  "labels": [
   ".pp-pg-total:before"
  ],
  "ids": [
   ".Btn2-purple:before"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character count text flex container",
  "labels": [
   ".profile-badge-flex-inner"
  ],
  "ids": [
   ".Btn2-purple>.css-wd8hou"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character count number",
  "labels": [
   ".pp-pg-total-count",
   ".profile-badge-total-count"
  ],
  "ids": [
   ".Btn2-purple>.css-wd8hou strong"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character count text",
  "labels": [
   ".pp-pg-total-text",
   ".profile-badge-total-text"
  ],
  "ids": [
   ".Btn2-purple>.css-wd8hou p"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Search bar + filter button + latest menu main container",
  "labels": [],
  "ids": [
   ".css-zdpt2t"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "…container layer 2",
  "labels": [
   ".profile-filters-flex-outer"
  ],
  "ids": [
   ".css-1cdqd3a"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "…flex container (aligns the 3 items)",
  "labels": [
   ".profile-filters-flex-inner"
  ],
  "ids": [
   ".css-mcoi9a"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character search bar main container",
  "labels": [
   ".profile-filters-flex-inner-hassearchfilter"
  ],
  "ids": [
   ".css-1jy826p"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character search bar container layer 2",
  "labels": [
   ".profile-character-search-input-group"
  ],
  "ids": [
   ".css-1jy826p>.css-1y0e7gb"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Character search bar input",
  "labels": [
   ".pp-fl-search-input",
   ".profile-character-search-input"
  ],
  "ids": [
   ".css-3rot3"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Tag filters button main container",
  "labels": [
   ".pp-fl-filter-button",
   ".profile-filter-button"
  ],
  "ids": [
   ".css-1n2in4t"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Tag filters icon",
  "labels": [
   ".pp-fl-filter-button svg",
   ".profile-filter-button svg"
  ],
  "ids": [
   ".css-1n2in4t svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Latest filtering menu main container",
  "labels": [
   ".profile-filters-flex-inner-onorderchanged"
  ],
  "ids": [
   ".css-1i3ggec"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Latest filtering menu container layer 2",
  "labels": [
   ".transparent"
  ],
  "ids": [
   ".css-b62m3t-container"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Latest menu button background container",
  "labels": [],
  "ids": [
   ".transparent .react-select__control"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Latest menu selected filter text container",
  "labels": [],
  "ids": [
   ".transparent .react-select__value-container"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Latest menu selected filter text",
  "labels": [],
  "ids": [
   ".transparent .react-select__value-container>div"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Latest menu down arrow outer container",
  "labels": [],
  "ids": [
   ".css-1wy0on6"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Latest menu line separator (between 'Latest' and arrow)",
  "labels": [],
  "ids": [
   ".css-1wy0on6 span"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Latest menu down arrow inner container",
  "labels": [],
  "ids": [
   ".transparent .react-select__dropdown-indicator"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Latest menu down arrow",
  "labels": [],
  "ids": [
   ".css-8mmkcg",
   ".transparent .react-select__dropdown-indicator svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Sub-container 2 (bot card grid)",
  "labels": [
   ".pp-cc-list-container"
  ],
  "ids": [
   ".css-2n7zf2>div>div:nth-child(2)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Sub-container 3 (page counter / footer)",
  "labels": [
   ".profile-pagination-flex-outer"
  ],
  "ids": [
   ".css-2n7zf2>div>div:nth-child(3)",
   ".css-1pfxi6a"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Page arrows + page number flex container",
  "labels": [
   ".profile-pagination-prev-hstack"
  ],
  "ids": [
   ".css-1igwmid"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "< page arrow container",
  "labels": [
   ".pp-pg-prev-button",
   ".profile-pagination-prev-button"
  ],
  "ids": [
   ".css-1gpctw1:nth-of-type(1)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "< page arrow",
  "labels": [
   ".pp-pg-prev-button svg",
   ".profile-pagination-prev-button svg"
  ],
  "ids": [
   ".css-1gpctw1:nth-of-type(1) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Page number container",
  "labels": [
   ".profile-pagination-flex-inner"
  ],
  "ids": [
   ".css-1bejyq4"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Page number",
  "labels": [
   ".pp-pg-page-button"
  ],
  "ids": [
   ".css-1bejyq4>div"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "Active page number",
  "labels": [
   ".pp-pg-page-button-active",
   ".profile-pagination-page-button-active"
  ],
  "ids": []
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "> page arrow container",
  "labels": [
   ".pp-pg-next-button",
   ".profile-pagination-next-button-icon"
  ],
  "ids": [
   ".css-1gpctw1:nth-of-type(2)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character / Bot Card Page Portion",
  "element": "> page arrow",
  "labels": [
   ".pp-pg-next-button svg",
   ".profile-pagination-next-button-icon svg"
  ],
  "ids": [
   ".css-1gpctw1:nth-of-type(2) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character Filtering Menu (Latest Menu)",
  "element": "Menu main pop-up container",
  "labels": [],
  "ids": [
   ".transparent .react-select__menu",
   ".css-1nmdiq5-menu"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character Filtering Menu (Latest Menu)",
  "element": "Menu main background layer",
  "labels": [
   ".react-select__menu-list"
  ],
  "ids": [
   ".css-qr46ko"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character Filtering Menu (Latest Menu)",
  "element": "'Popular' option",
  "labels": [
   ".react-select__option:nth-of-type(1)"
  ],
  "ids": [
   ".css-qr46ko>div:nth-child(1)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character Filtering Menu (Latest Menu)",
  "element": "'Latest' option",
  "labels": [
   ".react-select__option:nth-of-type(2)"
  ],
  "ids": [
   ".css-qr46ko>div:nth-child(2)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character Filtering Menu (Latest Menu)",
  "element": "'Trending' option",
  "labels": [
   ".react-select__option:nth-of-type(3)"
  ],
  "ids": [
   ".css-qr46ko>div:nth-child(3)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character Filtering Menu (Latest Menu)",
  "element": "'Trending 24h' option",
  "labels": [
   ".react-select__option:nth-of-type(4)"
  ],
  "ids": [
   ".css-qr46ko>div:nth-child(4)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character Filtering Menu (Latest Menu)",
  "element": "Selected option",
  "labels": [],
  "ids": [
   ".transparent .react-select__option--is-selected"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Character Filtering Menu (Latest Menu)",
  "element": "Hovered option",
  "labels": [],
  "ids": [
   ".transparent .react-select__option:hover"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Filter pop-up overlay",
  "labels": [
   ".pp-fl-modal-overlay",
   ".profile-filter-modal-modal-overlay"
  ],
  "ids": [
   ".chakra-modal__overlay"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Main filter pop-up container",
  "labels": [
   ".chakra-modal__content-container"
  ],
  "ids": [
   ".css-16r55pk"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Filter pop-up main flex container",
  "labels": [
   ".pp-fl-modal",
   ".profile-filter-modal-content"
  ],
  "ids": [
   ".css-1n6p0lj"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "'Filters' header container",
  "labels": [
   ".pp-fl-modal-header",
   ".profile-filter-modal-header"
  ],
  "ids": [
   ".css-dcyl1x"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "'X' close button container",
  "labels": [
   ".pp-fl-modal-close",
   ".profile-filter-modal-close"
  ],
  "ids": [
   ".css-lyo4r5"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "'X' close button icon",
  "labels": [
   ".pp-fl-modal-close svg"
  ],
  "ids": [
   ".css-lyo4r5 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Tags section container",
  "labels": [
   ".pp-fl-modal-body",
   ".profile-filter-modal-body"
  ],
  "ids": [
   ".css-1x51k4p"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Tags section container layer 2",
  "labels": [
   ".pp-fl-panel",
   ".profile-filter-modal-body-flex"
  ],
  "ids": [
   ".css-18936vg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Tags section container layer 3 (purpose unknown)",
  "labels": [
   ".pp-fl-tags",
   ".profile-filter-modal-body-tags-flex-box"
  ],
  "ids": [
   ".css-18936vg>div>.css-0"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "'Tags' header container",
  "labels": [
   ".pp-fl-tags-heading",
   ".profile-filter-modal-body-tags-flex-box-heading"
  ],
  "ids": [
   ".css-s89k0f"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Tags section container layer 4 (purpose unknown)",
  "labels": [
   ".pp-fl-tags-filter",
   ".profile-filter-tags-filter"
  ],
  "ids": [
   ".css-18936vg>div>div>.css-0"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Filter tags + buttons main container",
  "labels": [
   ".pp-fl-tags-list",
   ".profile-filter-tags-list"
  ],
  "ids": [
   "._container_14k4u_1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Filter tags main container",
  "labels": [
   ".pp-fl-tags-container",
   ".pp-fl-tags-list-container",
   ".profile-filter-tags-container"
  ],
  "ids": [
   "._tagsContainer_14k4u_10"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Collapsed filter tags flex container",
  "labels": [
   ".pp-fl-tags-scroll-wrapper",
   ".profile-filter-tags-scroll-wrapper"
  ],
  "ids": [
   "._collapsedContainerWrapper_14k4u_78"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Collapsed filter right gradient",
  "labels": [],
  "ids": [
   "._gradientRight_14k4u_36"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Collapsed filter left gradient",
  "labels": [],
  "ids": [
   "._gradientLeft_14k4u_19"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Collapsed filter right arrow button",
  "labels": [
   ".pp-fl-tags-scroll-right"
  ],
  "ids": [
   "._navigationButtonRight_14k4u_138"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Collapsed filter right arrow > icon",
  "labels": [
   ".pp-fl-tags-scroll-right svg"
  ],
  "ids": [
   "._navigationButtonRight_14k4u_138 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Collapsed filter left arrow button",
  "labels": [
   ".pp-fl-tags-scroll-left"
  ],
  "ids": [
   "._navigationButtonLeft_14k4u_129"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Collapsed filter left arrow < icon",
  "labels": [
   ".pp-fl-tags-scroll-left svg"
  ],
  "ids": [
   "._navigationButtonLeft_14k4u_129 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Expand filters button",
  "labels": [
   ".pp-fl-tags-expand"
  ],
  "ids": [
   "._expandButton_14k4u_153"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Expand filters button icon",
  "labels": [
   ".pp-fl-tags-expand svg"
  ],
  "ids": [
   "._expandButton_14k4u_153 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Collapsed filters flex container",
  "labels": [
   ".pp-fl-tags-scroll",
   ".pp-fl-tags-list-scroll",
   ".profile-filter-tags-scroll"
  ],
  "ids": [
   "._collapsedContainer_14k4u_78"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Expanded filters flex container",
  "labels": [
   ".pp-fl-tags-scroll-expanded",
   ".profile-filter-tags-scroll-expanded"
  ],
  "ids": [
   "._expanded_14k4u_14"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Filter tag outer container",
  "labels": [],
  "ids": [
   "._motionDiv_14k4u_142"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Filter tags flex container",
  "labels": [
   ".pp-fl-tag",
   ".profile-filter-tag"
  ],
  "ids": [
   "._container_fgxac_1"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Tag Filter Pop-Up Screen",
  "element": "Filter tag styling",
  "labels": [
   ".pp-fl-tag-button",
   ".profile-filter-tag-button"
  ],
  "ids": [
   "._tag_fgxac_6"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "Main menu container",
  "labels": [],
  "ids": [
   ".css-mzi0gq"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "Menu options container",
  "labels": [
   ".pp-top-bar-app-menu-list",
   ".profile-top-bar-app-menu-list"
  ],
  "ids": [
   ".css-197qci7"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "Empty container parent layer (purpose unknown)",
  "labels": [],
  "ids": [
   ".css-197qci7>.css-0"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "All menu options",
  "labels": [
   ".pp-top-bar-app-menu-list-item",
   ".profile-top-bar-app-menu-list a"
  ],
  "ids": [
   ".css-197qci7 a"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Janitor+' option",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/plus\"]"
  ],
  "ids": [
   "._plusItem_1xv0r_20"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Janitor+' icon",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/plus\"] svg"
  ],
  "ids": [
   "._plusItem_1xv0r_20 svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Profile' option",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href*=\"/profiles/\"]"
  ],
  "ids": [
   ".css-197qci7>a:first-child",
   ".css-197qci7 a:nth-of-type(2)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Profile' icon",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href*=\"/profiles/\"] svg"
  ],
  "ids": [
   ".css-197qci7>a:first-child svg",
   ".css-197qci7 a:nth-of-type(2) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'My Characters' option",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/my_characters\"]"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(3)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'My Characters' icon",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/my_characters\"] svg"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(3) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Scripts beta' option",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/scripts\"]"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(4)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Scripts beta' icon",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/scripts\"] svg"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(4) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'My Chats' option",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/my_chats\"]"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(5)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'My Chats' icon",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/my_chats\"] svg"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(5) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'My Personas' option",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/my_personas\"]"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(6)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'My Personas' icon",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/my_personas\"] svg"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(6) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Following' option",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/profile-settings?tab=following&connectionsTab=following\"]"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(7)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Following' icon",
  "labels": [
   "(same selector as above)  svg"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(7) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Blocks' option",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/profile-settings?tab=blocks&connectionsTab=blockedCreators\"]"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(8)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Blocks' icon",
  "labels": [
   "(same selector as above)  svg"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(8) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Media Library' option",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/media-library\"]"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(9)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Media Library' icon",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/media-library\"] svg"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(9) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Settings' option",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/profile-settings\"]"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(10)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Settings' icon",
  "labels": [
   ".pp-top-bar-app-menu-list-item[href=\"/profile-settings\"] svg"
  ],
  "ids": [
   ".css-197qci7 a:nth-of-type(10) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Log Out' option",
  "labels": [
   ".pp-top-bar-app-menu-list-item:last-child"
  ],
  "ids": [
   ".css-197qci7 a:last-child",
   ".css-197qci7 a:nth-of-type(11)"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "'Log Out' icon",
  "labels": [
   ".pp-top-bar-app-menu-list-item:last-child svg"
  ],
  "ids": [
   ".css-197qci7 a:last-child svg",
   ".css-197qci7 a:nth-of-type(11) svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "User Menu",
  "element": "All line spacers between menu options",
  "labels": [],
  "ids": [
   ".css-197qci7 hr"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Main parent container",
  "labels": [
   ".pp-top-bar-notifications-popover",
   ".profile-top-bar-notifications-popover"
  ],
  "ids": [
   "[class*=\"notificationsPopover_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Main parent container styling pseudo-element",
  "labels": [
   ".pp-top-bar-notifications-popover:before"
  ],
  "ids": [
   "[class*=\"notificationsPopover_\"]:before"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "'Notifications' title container",
  "labels": [
   ".pp-top-bar-notifications-popover-header",
   ".profile-top-bar-notifications-popover-header"
  ],
  "ids": [
   "[class*=\"popoverHeader_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "'Notifications' title text",
  "labels": [
   ".pp-top-bar-notifications-popover-title",
   ".profile-top-bar-notifications-popover-title"
  ],
  "ids": [
   "[class*=\"popoverTitle_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Buttons (trash, read all, close) flex container",
  "labels": [
   ".pp-top-bar-notifications-popover-actions",
   ".profile-top-bar-notifications-popover-actions"
  ],
  "ids": [
   "[class*=\"headerActions_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Delete All container",
  "labels": [
   ".pp-top-bar-notifications-delete-all"
  ],
  "ids": [
   "[class*=\"deleteAllButton_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Delete All trash icon",
  "labels": [
   ".pp-top-bar-notifications-delete-all svg"
  ],
  "ids": [
   "[class*=\"deleteAllButton_\"] svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Read All container",
  "labels": [
   ".pp-top-bar-notifications-mark-all-read"
  ],
  "ids": [
   "[class*=\"markAllReadButton_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Read All checkmarks icon",
  "labels": [
   ".pp-top-bar-notifications-mark-all-read svg"
  ],
  "ids": [
   "[class*=\"markAllReadButton_\"] svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Close menu container",
  "labels": [
   ".pp-top-bar-notifications-close"
  ],
  "ids": [
   "[class*=\"closeButton_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Close menu 'X' icon",
  "labels": [
   ".pp-top-bar-notifications-close svg"
  ],
  "ids": [
   "[class*=\"closeButton_\"] svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "'View All' notifications button",
  "labels": [
   ".pp-top-bar-notifications-view-all",
   ".profile-top-bar-notifications-view-all"
  ],
  "ids": [
   "a[href=\"/notifications\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "List of notifications container",
  "labels": [
   ".pp-top-bar-notifications-list"
  ],
  "ids": [
   "[class*=\"notificationsList_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Notification container",
  "labels": [
   ".pp-top-bar-notifications-item"
  ],
  "ids": [
   "[class*=\"notificationItem_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Notification image outer container",
  "labels": [
   ".pp-top-bar-notifications-item-avatar-section"
  ],
  "ids": [
   "[class*=\"avatarSection_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Notification image inner container",
  "labels": [
   ".pp-top-bar-notifications-item-avatar"
  ],
  "ids": [
   "[class*=\"avatarContainer_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Notification bot image",
  "labels": [],
  "ids": [
   "[class=\"notificationItem_\"] img:nth-of-type(1)",
   "[class=\"characterAvatar_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Notification user image",
  "labels": [],
  "ids": [
   "[class=\"notificationItem_\"] img:nth-of-type(2)",
   "[class=\"userAvatar_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Text parent container",
  "labels": [
   ".pp-top-bar-notifications-item-content-wrapper"
  ],
  "ids": [
   "[class*=\"contentWrapper_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Text flex container",
  "labels": [
   ".pp-top-bar-notifications-item-content"
  ],
  "ids": [
   "[class*=\"contentWrapper_\"]>div"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Subject line (first line of text)",
  "labels": [
   ".pp-top-bar-notifications-item-subject"
  ],
  "ids": [
   "[class*=\"subject_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Content text (second line)",
  "labels": [
   ".pp-top-bar-notifications-item-body"
  ],
  "ids": [
   "[class*=\"body_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Timestamp (third line)",
  "labels": [
   ".pp-top-bar-notifications-item-timestamp"
  ],
  "ids": [
   "[class*=\"timestamp_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Delete/archive button container",
  "labels": [
   ".pp-top-bar-notifications-item-archive-section"
  ],
  "ids": [
   "[class*=\"archiveSection_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Delete/archive button",
  "labels": [
   ".pp-top-bar-notifications-item-archive"
  ],
  "ids": [
   "[aria-label=\"Archive notification\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Trash can icon",
  "labels": [
   ".pp-top-bar-notifications-item-archive svg"
  ],
  "ids": [
   "[aria-label=\"Archive notification\"] svg"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Unread notification text parent container",
  "labels": [],
  "ids": [
   "[class*=\"contentWrapperUnread_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Unread notification subject line text",
  "labels": [],
  "ids": [
   "[class*=\"subjectUnread_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Unread notification indicator bar",
  "labels": [
   ".pp-top-bar-notifications-item-unread"
  ],
  "ids": [
   "[class*=\"unreadIndicator_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Username highlight",
  "labels": [],
  "ids": [
   "[class*=\"highlightUsername_\"]"
  ]
 },
 {
  "group": "Profile Page Elements",
  "sub": "Notifications Menu Pop-Up",
  "element": "Character name highlight",
  "labels": [],
  "ids": [
   "[class*=\"highlightCharacterBody_\"]"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "Header parent container",
  "labels": [
   ".pp-top-header"
  ],
  "ids": [
   ".css-1n2ma9q"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "Main container",
  "labels": [
   ".pp-top-bar",
   ".profile-top-bar (labels shared with desktop)"
  ],
  "ids": [
   ".css-1hv2wai"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "'Back' button section container",
  "labels": [],
  "ids": [
   ".css-13qw20c"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "'Back' button container",
  "labels": [
   ".pp-top-bar-back-button",
   ".profile-top-bar-back-button"
  ],
  "ids": [
   ".css-1v7jfo7",
   ".css-13qw20c>button"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "< icon",
  "labels": [
   ".pp-top-bar-back-button svg"
  ],
  "ids": [
   ".css-1dwr89y",
   ".css-13qw20c>button span",
   ".css-13qw20c>button svg"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "'Back' text",
  "labels": [
   ".pp-top-bar-back-button p"
  ],
  "ids": [
   ".css-1rokoft",
   ".css-13qw20c>button p"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "'janitorai' section container",
  "labels": [],
  "ids": [
   ".css-1nsonir"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "'janitorai' section inner container (hides text overflow)",
  "labels": [],
  "ids": [
   ".css-1o4wo1x",
   ".css-1nsonir>div"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "'janitorai' text",
  "labels": [
   ".pp-top-bar-title",
   ".profile-top-bar-title"
  ],
  "ids": [
   ".css-16g2f4q",
   ".css-1nsonir p"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "Notification and block button section container",
  "labels": [],
  "ids": [
   ".css-7f563p"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "⋮ block/report options container",
  "labels": [],
  "ids": [
   ".css-7f563p>div:first-child"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "⋮ block/report options container inner",
  "labels": [],
  "ids": [
   ".css-7f563p>div:first-child>div"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "⋮ block/report options button",
  "labels": [
   "button[aria-label=\"options\"]"
  ],
  "ids": []
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "⋮ block/report options button dots",
  "labels": [
   "button[aria-label=\"options\"] svg"
  ],
  "ids": []
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "⋮ block/report pop-up container",
  "labels": [
   "button[aria-label=\"options\"] + div"
  ],
  "ids": []
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "⋮ block/report pop-up Report option",
  "labels": [
   "button[aria-label=\"options\"] + div>button:first-child"
  ],
  "ids": []
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Header",
  "element": "⋮ block/report pop-up Block option",
  "labels": [
   "button[aria-label=\"options\"] + div>button:last-child"
  ],
  "ids": []
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "Main footer container",
  "labels": [
   ".pp-mnb-wrapper"
  ],
  "ids": [
   ".css-1fox4tu"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "Links/icon container",
  "labels": [
   ".pp-mnb-container"
  ],
  "ids": [
   ".css-1cyxci9"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "All links (excluding user menu)",
  "labels": [
   ".pp-mnb-container a"
  ],
  "ids": [
   ".css-1cyxci9 a"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "All link containers (excluding user menu)",
  "labels": [
   ".pp-mnb-item"
  ],
  "ids": [
   ".css-1l8kxqv"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "All icons (excluding user menu)",
  "labels": [
   ".pp-mnb-container svg"
  ],
  "ids": [
   ".css-1cyxci9 svg"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "Home menu link",
  "labels": [
   ".pp-mnb-container a[href=\"/\"]"
  ],
  "ids": [
   ".css-1cyxci9>a:nth-child(1)"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "Home menu icon (house)",
  "labels": [
   ".pp-mnb-item:nth-of-type(1) svg"
  ],
  "ids": [
   ".css-1cyxci9>a:nth-child(1) svg"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "Chats menu link",
  "labels": [
   ".pp-mnb-container a[href=\"/my_chats\"]"
  ],
  "ids": [
   ".css-1cyxci9>a:nth-child(2)"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "Chats menu icon (chat bubble)",
  "labels": [
   ".pp-mnb-item:nth-of-type(2) svg"
  ],
  "ids": [
   ".css-1cyxci9>a:nth-child(2) svg"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "Search/Explore menu link",
  "labels": [
   ".pp-mnb-container a[href*=\"/search\"]"
  ],
  "ids": [
   ".css-1cyxci9>a:nth-child(3)"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "Search/Explore menu icon (magnifying glass)",
  "labels": [
   ".pp-mnb-item:nth-of-type(3) svg"
  ],
  "ids": [
   ".css-1cyxci9o>a:nth-child(3) svg"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "User menu link container",
  "labels": [
   ".pp-mnb-container>div:last-child"
  ],
  "ids": [
   ".css-1cyxci9>div:last-child",
   ".css-dvxtzn"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "User menu link flex container",
  "labels": [
   ".pp-mnb-user-menu"
  ],
  "ids": [
   ".css-1ib4t17"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "User menu link transformation layer",
  "labels": [
   ".pp-top-bar-app-menu"
  ],
  "ids": [
   ".css-8mfon9"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "User menu link inner container layer 1",
  "labels": [
   ".pp-top-bar-app-menu>span"
  ],
  "ids": [
   ".css-xl71ch"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "User menu link inner container layer 2 (contains transition)",
  "labels": [],
  "ids": [
   ".css-2jhocq"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "User menu avatar image container",
  "labels": [
   ".pp-top-bar-app-menu span:nth-of-type(2)"
  ],
  "ids": [
   ".css-1fgzixv"
  ]
 },
 {
  "group": "Mobile / Small Viewport Elements",
  "sub": "Mobile Footer Menu",
  "element": "User menu avatar image",
  "labels": [
   ".pp-mnb-container img"
  ],
  "ids": [
   ".css-mnkk9b"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "All tooltip text boxes",
  "labels": [],
  "ids": [
   ".css-jdhqy4>div"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "Tooltip arrow outer container",
  "labels": [
   ".chakra-tooltip__arrow-wrapper"
  ],
  "ids": [
   ".css-jdhqy4 .css-0"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "Tooltip arrow inner container",
  "labels": [
   ".chakra-tooltip__arrow"
  ],
  "ids": [
   ".css-1ugx2pr (needs !important to change)"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "Followed/unfollowed green pop-up (toast) container",
  "labels": [
   "[data-sonner-toaster]"
  ],
  "ids": [
   ".sonner-toast-container"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "Followed/unfollowed green pop-up",
  "labels": [
   ".sonner-toast-container [data-sonner-toast][data-type=success]"
  ],
  "ids": [
   ".sonner-toast-container li"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "Followed/unfollowed green checkmark icon",
  "labels": [
   ".sonner-toast-container [data-sonner-toast][data-type=success] [data-icon]"
  ],
  "ids": [
   ".sonner-toast-container li>div:first-child"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "Followed/unfollowed green text container",
  "labels": [
   "[data-sonner-toast][data-styled=true] [data-content]"
  ],
  "ids": [
   ".sonner-toast-container li>div:last-child"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "Followed/unfollowed green text",
  "labels": [
   "[data-sonner-toast][data-styled=true] [data-title]"
  ],
  "ids": [
   ".sonner-toast-container li>div:last-child>div"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "Follow/unfollow tooltip text",
  "labels": [
   ".profile-uc-follow-tooltip"
  ],
  "ids": [
   ".css-1mdyyu3"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "Follow/unfollow green popup behind (when there are 2 pop-ups)",
  "labels": [
   "[data-sonner-toast][data-expanded=false][data-front=false]"
  ],
  "ids": []
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "'Block this creator' tooltip parent container",
  "labels": [
   "div:has(>.pp-uc-options-menu-list)"
  ],
  "ids": [
   ".css-r6z5ec"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "'Block this creator' tooltip inner container",
  "labels": [
   ".pp-uc-options-menu-list",
   "#menu-list-public-profile-block-menu"
  ],
  "ids": [
   ".css-1kk6pgz"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "'Block this creator' tooltip flex container",
  "labels": [
   ".pp-uc-options-menu-item"
  ],
  "ids": [
   ".css-1f9kvnj"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "'Block this creator' X close button",
  "labels": [
   ".pp-uc-options-menu-item span:first-child"
  ],
  "ids": [
   ".css-7halv9"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "'Block this creator' X close button icon",
  "labels": [
   ".pp-uc-options-menu-item span:first-child svg"
  ],
  "ids": [
   ".css-7halv9 svg"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "'Block this creator' text",
  "labels": [
   ".pp-uc-options-menu-item span:last-child"
  ],
  "ids": [
   ".css-1izfp9f span:last-child"
  ]
 },
 {
  "group": "Miscellaneous Elements",
  "sub": "Tooltips (Pop-Up Text Boxes)",
  "element": "'Report this profile' tooltip flex container",
  "labels": [
   ".pp-uc-options-menu-item:nth-of-type(2)"
  ],
  "ids": [
   ".css-1f9kvnj"
  ]
 }
];
