/*
 * JanitorAI's tag ids, and the two URL shapes a tag chip can link to.
 *
 * A regular tag is a numbered filter on the browse page; anything not in
 * JanitorAI's own list is a creator-made "custom tag" and is linked by name
 * instead. Hardcoded bio markup has to spell these links out in full — the
 * site's own tag chips are generated by its React app, which never runs inside
 * an About Me block — so this table is what lets the studio write them for you.
 *
 * Ids were read off the live browse page; gaps in the numbering (4, 7, 27, …)
 * are tags this list doesn't have, not mistakes. An unknown name falls back to
 * a custom-tag link, which is also the right answer for a genuine custom tag.
 */
(function (global) {
  'use strict';

  var IDS = {
    male: 1, female: 2, 'non-binary': 3, oc: 5, fictional: 6, game: 8,
    anime: 9, historical: 10, royalty: 11, detective: 12, hero: 13,
    villain: 14, magical: 15, 'non-human': 16, monster: 17,
    'monster girl': 18, alien: 19, robot: 20, politics: 21, vampire: 22,
    giant: 23, openai: 24, elf: 25, 'multiple characters': 26,
    'dominant character': 28, submissive: 29, 'scenario card': 30,
    'pokemon': 31, 'assistant card': 32, 'non english': 34,
    philosophy: 36, rpg: 38, religion: 39, books: 41, anypov: 42,
    angst: 43, 'demi-human character': 44, 'enemies to lovers': 45,
    smut: 46, 'mlm (yaoi)': 47, 'wlw (yuri)': 48, 'dead dove': 49,
    fluff: 50, horror: 51, comedy: 52, furry: 53, fempov: 54,
    malepov: 55, switch: 56, trans: 57, 'the beginning': 59,
    'sci fi': 60, 'music mania': 61
  };

  /* Spellings people actually type, mapped onto the canonical key above. */
  var ALIASES = {
    nonbinary: 'non-binary', enby: 'non-binary', nb: 'non-binary',
    'original character': 'oc', nonhuman: 'non-human',
    'monstergirl': 'monster girl', 'demi-human': 'demi-human character',
    'demihuman': 'demi-human character', dominant: 'dominant character',
    dom: 'dominant character', sub: 'submissive', scenario: 'scenario card',
    assistant: 'assistant card', yaoi: 'mlm (yaoi)', mlm: 'mlm (yaoi)',
    yuri: 'wlw (yuri)', wlw: 'wlw (yuri)', deaddove: 'dead dove',
    'any pov': 'anypov', 'fem pov': 'fempov', 'male pov': 'malepov',
    scifi: 'sci fi', 'sci-fi': 'sci fi', 'nonenglish': 'non english',
    'non-english': 'non english', beginning: 'the beginning',
    music: 'music mania', pokémon: 'pokemon'
  };

  /* JanitorAI prefixes its own chips with an emoji ("👩‍🦰 Female") and a
   * captured card carries that through, so a name arrives with joiners and
   * surrogate pairs attached. Strip those, fold accents down ("Pokémon" ->
   * "Pokemon", which is how the id table spells it), and drop anything left
   * that the real tag names never use. */
  function clean(name) {
    return String(name || '')
      .normalize('NFD').replace(/[̀-ͯ]/g, '')
      .replace(/[\uD800-\uDBFF][\uDC00-\uDFFF]/g, ' ')
      .replace(/[\uD800-\uDFFF]|‍|️|⃣/g, '')
      .replace(/[^\w\s()\-+&']/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
  }

  /* The key this name is stored under, following aliases. */
  function key(name) {
    var k = clean(name).toLowerCase();
    if (IDS[k] != null) return k;
    if (ALIASES[k] && IDS[ALIASES[k]] != null) return ALIASES[k];
    return null;
  }

  function idOf(name) {
    var k = key(name);
    return k ? IDS[k] : null;
  }

  /* A class-safe, url-safe form: "Monster Girl" -> "monster-girl". */
  function slug(name) {
    return clean(name).toLowerCase().replace(/[^\w]+/g, '-').replace(/^-+|-+$/g, '') || 'tag';
  }

  /*
   * Where a chip links. Numbered tags go to the browse filter; everything else
   * to the custom-tag search, which is how creator tags are browsed.
   */
  function url(name) {
    var id = idOf(name);
    if (id != null) {
      return 'https://janitorai.com/?mode=all&sort=popular&tag_id=' + id + '&page=1&segment=popular';
    }
    return 'https://janitorai.com/?segment=popular&view=all&custom_tags=' +
      encodeURIComponent(clean(name).toLowerCase().replace(/\s+/g, '')) + '&sort=popular';
  }

  /* Display form: the canonical spelling for a known tag, the creator's own
   * spelling for a custom one. */
  var LABELS = {};
  Object.keys(IDS).forEach(function (k) { LABELS[k] = k; });
  ['oc', 'rpg', 'anypov', 'fempov', 'malepov', 'openai'].forEach(function (k) {
    LABELS[k] = k.toUpperCase();
  });

  function label(name) {
    var k = key(name);
    if (!k) return clean(name);
    if (LABELS[k] !== k) return LABELS[k];
    return k.replace(/\b\w/g, function (c) { return c.toUpperCase(); });
  }

  /* Tags that are ratings rather than filters: the site renders them as plain
   * chips with no link, so hardcoded markup shouldn't link them either. */
  var UNLINKED = { limitless: 1, sfw: 1, nsfw: 1 };

  function isLinkable(name) { return !UNLINKED[clean(name).toLowerCase()]; }

  global.JaiTags = {
    ids: IDS,
    clean: clean,
    idOf: idOf,
    slug: slug,
    url: url,
    label: label,
    isLinkable: isLinkable,
    names: Object.keys(IDS)
  };
})(window);
