#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Turns Puppy's JanitorAI profile CSS reference (markdown) into js/reference.js,
the data behind the app's searchable selector browser.

Run:  python tools/build_reference.py [path-to-guide.md]
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SRC = os.path.join(
    os.path.expanduser("~"), "Downloads", "janitorai-css-reference.md"
)
OUT = os.path.join(ROOT, "js", "reference.js")

# Sections that describe elements; everything else in the guide is prose,
# changelog or the disabled-feature list, which lives in js/lint.js instead.
SKIP_SECTIONS = {
    "Element Changes (ID History)",
    "Element Label Updates",
    "Disabled CSS / HTML Properties on JAI",
    "Contents",
    "How to use this guide",
}


def clean(cell):
    """Markdown table cell -> plain text, keeping selector punctuation."""
    cell = cell.strip()
    cell = re.sub(r"\*\((.*?)\)\*", r"(\1)", cell)   # *(prev. .css-x)*
    cell = re.sub(r"\*\*(.*?)\*\*", r"\1", cell)
    cell = re.sub(r"\*(.*?)\*", r"\1", cell)
    cell = cell.replace("`", "")
    return cell.strip()


def split_selectors(cell):
    """A cell may hold several equivalent selectors separated by ' / '."""
    if not cell or cell in ("N/A", "—", "-"):
        return []
    # Drop the trailing "(prev. …)" note before splitting.
    cell = re.sub(r"\((?:prev\.|formerly|ID shared|may be shared)[^)]*\)", "", cell)
    parts = [p.strip() for p in cell.split(" / ")]
    return [p for p in parts if p and p not in ("N/A", "—", "-")]


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    if not os.path.exists(src):
        sys.exit("guide not found: %s" % src)

    with open(src, encoding="utf-8") as fh:
        lines = fh.read().splitlines()

    entries = []
    group = subgroup = ""
    in_table = False

    for line in lines:
        heading = re.match(r"^(#{2,3})\s+(.*)$", line)
        if heading:
            title = clean(heading.group(2))
            if heading.group(1) == "##":
                group, subgroup = title, ""
            else:
                subgroup = title
            in_table = False
            continue

        if not line.startswith("|"):
            in_table = False
            continue

        cells = [c for c in line.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        if re.match(r"^[\s:|-]+$", "|".join(cells)):
            in_table = True          # the ---|---|--- separator row
            continue
        if not in_table:
            continue                  # header row

        if group in SKIP_SECTIONS:
            continue

        element = clean(cells[0])
        labels = split_selectors(clean(cells[1]))
        ids = split_selectors(clean(cells[2]))
        if not element or not (labels or ids):
            continue

        entries.append(
            {
                "group": group,
                "sub": subgroup,
                "element": element,
                # Labels are stable across deploys; emotion IDs are not, so the
                # UI shows labels first and treats IDs as a fallback.
                "labels": labels,
                "ids": ids,
            }
        )

    payload = json.dumps(entries, ensure_ascii=False, indent=1)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(
            "/* Generated by tools/build_reference.py — do not edit by hand.\n"
            " * Source: Puppy's JanitorAI Profile Page CSS Reference. */\n"
            "window.JAI_REFERENCE = %s;\n" % payload
        )

    groups = []
    for e in entries:
        key = (e["group"], e["sub"])
        if key not in groups:
            groups.append(key)
    print("%d entries across %d sections -> js/reference.js" % (len(entries), len(groups)))


if __name__ == "__main__":
    main()
